### ISSUE TITLE
Error: not supported: external module

### ISSUE THREAD

**Issue by aberenyi** [snyk/snyk#100]
- `node -v`: `v8.1.4`
- `npm -v`: `5.2.0`
- `snyk -v`: `1.38.1`
- Command run: ` snyk protect`

### Expected behaviour
To patch the vulnerable packages successfully.

### Actual behaviour
Fails with
```
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: not supported: external module: auth0-js@https://registry.npmjs.org/auth0-js/-/auth0-js-8.2.0.tgz
    at supported (/opt/project/node_modules/snyk-module/lib/index.js:142:15)
    at moduleToObject (/opt/project/node_modules/snyk-module/lib/index.js:61:10)
    at /opt/project/node_modules/snyk-resolve-deps/lib/logical.js:105:12
    at Array.map (native)
    at insertLeaf (/opt/project/node_modules/snyk-resolve-deps/lib/logical.js:104:40)
    at /opt/project/node_modules/snyk-resolve-deps/lib/logical.js:87:7
    at /opt/project/node_modules/snyk-resolve-deps/lib/walk.js:13:15
    at Array.forEach (native)
    at walk (/opt/project/node_modules/snyk-resolve-deps/lib/walk.js:12:21)
    at /opt/project/node_modules/snyk-resolve-deps/lib/walk.js:15:7
```

### Steps to reproduce
`npm i auth0-js && snyk protect`

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

```
  snyk protect { _: [ [Circular] ], debug: true } +0ms
  snyk ~~~~ LIVE RUN ~~~~ +352ms
  snyk checking for cli updates +4ms
  snyk add local true +61ms
  snyk add success false +3satabase...
  snyk add error-message not supported: external module: auth0-js@https://registry.npmjs.org/auth0-js/-/auth0-js-8.2.0.tgz +2ms
  snyk add error Error: not supported: external module: auth0-js@https://registry.npmjs.org/auth0-js/-/auth0-js-8.2.0.tgz
    at supported (/opt/project/node_modules/snyk-module/lib/index.js:142:15)
    at moduleToObject (/opt/project/node_modules/snyk-module/lib/index.js:61:10)
    at /opt/project/node_modules/snyk-resolve-deps/lib/logical.js:105:12
    at Array.map (native)
    at insertLeaf (/opt/project/node_modules/snyk-resolve-deps/lib/logical.js:104:40)
    at /opt/project/node_modules/snyk-resolve-deps/lib/logical.js:87:7
    at /opt/project/node_modules/snyk-resolve-deps/lib/walk.js:13:15
    at Array.project (native)
    at walk (/opt/project/node_modules/snyk-resolve-deps/lib/walk.js:12:21)
    at /opt/project/node_modules/snyk-resolve-deps/lib/walk.js:15:7 +0ms
  snyk add error-code 501 +0ms
  snyk add command protect +0ms
Error: not supported: external module: auth0-js@https://registry.npmjs.org/auth0-js/-/auth0-js-8.2.0.tgz
    at supported (/opt/project/node_modules/snyk-module/lib/index.js:142:15)
    at moduleToObject (/opt/project/node_modules/snyk-module/lib/index.js:61:10)
    at /opt/project/node_modules/snyk-resolve-deps/lib/logical.js:105:12
    at Array.map (native)
    at insertLeaf (/opt/project/node_modules/snyk-resolve-deps/lib/logical.js:104:40)
    at /opt/project/node_modules/snyk-resolve-deps/lib/logical.js:87:7
    at /opt/project/node_modules/snyk-resolve-deps/lib/walk.js:13:15
    at Array.forEach (native)
    at walk (/opt/project/node_modules/snyk-resolve-deps/lib/walk.js:12:21)
    at /opt/project/node_modules/snyk-resolve-deps/lib/walk.js:15:7
  snyk { command: 'bad-command',
  snyk   args: [ { debug: true } ],
  snyk   metadata:
  snyk    { local: true,
  snyk      success: false,
  snyk      'error-message': 'not supported: external module: auth0-js@https://registry.npmjs.org/auth0-js/-/auth0-js-8.2.0.tgz',
  snyk      error: 'Error: not supported: external module: auth0-js@https://registry.npmjs.org/auth0-js/-/auth0-js-8.2.0.tgz\n    at supported (/opt/project/node_modules/snyk-module/lib/index.js:142:15)\n    at moduleToObject (/opt/project/node_modules/snyk-module/lib/index.js:61:10)\n    at /opt/project/node_modules/snyk-resolve-deps/lib/logical.js:105:12\n    at Array.map (native)\n    at insertLeaf (/opt/project/node_modules/snyk-resolve-deps/lib/logical.js:104:40)\n    at /opt/project/node_modules/snyk-resolve-deps/lib/logical.js:87:7\n    at /opt/project/node_modules/snyk-resolve-deps/lib/walk.js:13:15\n    at Array.forEach (native)\n    at walk (/opt/project/node_modules/snyk-resolve-deps/lib/walk.js:12:21)\n    at /opt/project/node_modules/snyk-resolve-deps/lib/walk.js:15:7',
  snyk      'error-code': 501,
  snyk      command: 'protect' },
  snyk   version: '1.38.1',
  snyk   os: 'OS X',
  snyk   nodeVersion: 'v8.1.4',
  snyk   id: '927772423fc69ccf5e0c3fe8778f8f347d895f90',
  snyk   ci: false } +2ms
```

**Comment by aberenyi** [comment]
Solved by updating the package to the latest version. 

I still think the error message is not really useful.
