### ISSUE TITLE
not supported: external module

### ISSUE THREAD

**Issue by liesislukas** [snyk/snyk#103]
- `node -v`: 6.11.3
- `npm -v`: 5.3.0
- `snyk -v`: 1.40.3
- Command run: `snyk test --debug`

### Expected behaviour
pass

### Actual behaviour
burn to ashes with  not supported: external module

### Steps to reproduce

add `"body-parser": "https://registry.npmjs.org/body-parser/-/body-parser-1.14.2.tgz",` to package.json and run `snyk test`.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

```
Lukass-iMac:www lukas$ snyk test --debug
  snyk test { _: [ [Circular] ], debug: true } +0ms
  snyk checking for cli updates +275ms
  snyk add local true +39ms
  snyk add error-message not supported: external module: body-parser@https://registry.npmjs.org/body-parser/-/body-parser-1.14.2.tgz +1s
  snyk add error Error: not supported: external module: body-parser@https://registry.npmjs.org/body-parser/-/body-parser-1.14.2.tgz
    at supported (/usr/local/lib/node_modules/snyk/node_modules/snyk-module/lib/index.js:142:15)
    at moduleToObject (/usr/local/lib/node_modules/snyk/node_modules/snyk-module/lib/index.js:61:10)
    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/logical.js:105:12
    at Array.map (native)
    at insertLeaf (/usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/logical.js:104:40)
    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/logical.js:87:7
    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/walk.js:13:15
    at Array.forEach (native)
    at walk (/usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/walk.js:12:21)
    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/walk.js:15:7 +1ms
  snyk add error-code 501 +0ms
  snyk add command test +0ms
Error: not supported: external module: body-parser@https://registry.npmjs.org/body-parser/-/body-parser-1.14.2.tgz
    at supported (/usr/local/lib/node_modules/snyk/node_modules/snyk-module/lib/index.js:142:15)
    at moduleToObject (/usr/local/lib/node_modules/snyk/node_modules/snyk-module/lib/index.js:61:10)
    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/logical.js:105:12
    at Array.map (native)
    at insertLeaf (/usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/logical.js:104:40)
    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/logical.js:87:7
    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/walk.js:13:15
    at Array.forEach (native)
    at walk (/usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/walk.js:12:21)
    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/walk.js:15:7
  snyk { command: 'bad-command',
  snyk   args: [ { debug: true, packageManager: 'npm' } ],
  snyk   metadata:
  snyk    { local: true,
  snyk      'error-message': 'not supported: external module: body-parser@https://registry.npmjs.org/body-parser/-/body-parser-1.14.2.tgz',
  snyk      error: 'Error: not supported: external module: body-parser@https://registry.npmjs.org/body-parser/-/body-parser-1.14.2.tgz\n    at supported (/usr/local/lib/node_modules/snyk/node_modules/snyk-module/lib/index.js:142:15)\n    at moduleToObject (/usr/local/lib/node_modules/snyk/node_modules/snyk-module/lib/index.js:61:10)\n    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/logical.js:105:12\n    at Array.map (native)\n    at insertLeaf (/usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/logical.js:104:40)\n    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/logical.js:87:7\n    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/walk.js:13:15\n    at Array.forEach (native)\n    at walk (/usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/walk.js:12:21)\n    at /usr/local/lib/node_modules/snyk/node_modules/snyk-resolve-deps/lib/walk.js:15:7',
  snyk      'error-code': 501,
  snyk      command: 'test' },
  snyk   version: '1.40.3',
  snyk   os: 'OS X',
  snyk   nodeVersion: 'v6.11.3',
  snyk   id: '019a7e53617b87f9dbe6cfb9917c54a003c79c09',
  snyk   ci: false } +2ms

Lukass-iMac:www lukas$ node -v
v6.11.3
Lukass-iMac:www lukas$ npm -v
5.3.0
Lukass-iMac:www lukas$ snyk -v
1.40.3
```

**Comment by maban** [comment]
Hi @liesislukas, thanks for reporting this. I believe this has been fixed, and it's working for me locally. Could you update your version of snyk and try it again, and let me know if it's still a problem?

**Comment by liesislukas** [comment]
@maban not working on that codebase anymore, can't tell.

**Comment by lili2311** [comment]
:wave: This issue has not had a lot of activity for a while, we are closing. Please re-open if there is anything else further.
