### ISSUE TITLE
[🐛] 

### ISSUE THREAD

**Issue by garethr** [snyk/snyk#1045]
- `node -v`: v12.3.1
- `npm -v`: 6.14.1
- `snyk -v`: 1.297.4
- OS: macOS
- Command run: `snyk test`

### Expected behaviour

Snyk to not fail if it can't access the users home directory. If the `SNYK_TOKEN` environment variable is provided then it uses that for authentication.

### Actual behaviour

If the user home directory is not accessible by the process running Snyk then Snyk fails with an exception:

```
Error: EPERM: operation not permitted, open '/Users/garethr/.config/configstore/snyk.json.1775249875'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:490:32)
    at Function.writeFileSync [as sync] (/snapshot/snyk/node_modules/write-file-atomic/index.js:212:13)
    at Configstore.set all [as all] (/snapshot/snyk/node_modules/@snyk/configstore/index.js:58:20)
    at new Configstore (/snapshot/snyk/node_modules/@snyk/configstore/index.js:25:12)
    at Object.<anonymous> (/snapshot/snyk/dist/lib/user-config.js:5:18)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
```

### Steps to reproduce

Slightly different, but the same underlying issue. Set `HOME` to a directory that doesn't exist:

```console
$ export HOME=/sdd/sd
$ snyk test --docker ubuntu:18.0
Error: EROFS: read-only file system, mkdir '/sdd'
    at Object.fs.mkdirSync (fs.js:885:18)
    at make (/snapshot/snyk/node_modules/make-dir/index.js:61:12)
    at make (/snapshot/snyk/node_modules/make-dir/index.js:68:5)
    at make (/snapshot/snyk/node_modules/make-dir/index.js:68:5)
    at make (/snapshot/snyk/node_modules/make-dir/index.js:68:5)
    at Function.module.exports.sync (/snapshot/snyk/node_modules/make-dir/index.js:84:9)
    at Configstore.get all [as all] (/snapshot/snyk/node_modules/@snyk/configstore/index.js:34:13)
    at new Configstore (/snapshot/snyk/node_modules/@snyk/configstore/index.js:25:47)
    at Object.<anonymous> (/snapshot/snyk/dist/lib/user-config.js:5:18)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
```

**Comment by Azooze0533** [comment]
Ueywy****
