### ISSUE TITLE
[🐛] Snyk wizard broken version 1.316.0

### ISSUE THREAD

**Issue by ffriedl89** [snyk/snyk#1096]
- `node -v`: 12.16.1
- `npm -v`: 6.13.4
- `snyk -v`: 1.316.0
- OS: (e.g. OSX, Linux, Windows, ...) MacOS & Windows
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...) `snyk wizard`

### Expected behaviour
The wizard is running successfully

### Actual behaviour
It breaks with an error message stating to add the -d flag for a full stacktrace. 
```
An unknown error occurred. Please run with `-d` and include full trace when reporting to Snyk
```

### Steps to reproduce
run `snyk wizard`

### Debug log
```
snyk wizard { _: [ [Circular] ], debug: true } +0ms
Error: Cannot find module 'lodash'
Require stack:
- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/lib/protect/update.js
- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/lib/protect/index.js
- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/commands/protect/prompts.js
- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/commands/protect/wizard.js
- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/lib/hotload.js
- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/commands/index.js
- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/args.js
- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/src/lib/protect/update.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
  snyk analytics {
  args: [ { debug: true } ],
  command: 'bad-command',
  org: undefined,
  metadata: {
    'error-message': "Cannot find module 'lodash'\n" +
      'Require stack:\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/lib/protect/update.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/lib/protect/index.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/commands/protect/prompts.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/commands/protect/wizard.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/lib/hotload.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/commands/index.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/args.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/index.js',
    error: "Error: Cannot find module 'lodash'\n" +
      'Require stack:\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/lib/protect/update.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/lib/protect/index.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/commands/protect/prompts.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/commands/protect/wizard.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/lib/hotload.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/commands/index.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/args.js\n' +
      '- /Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/dist/cli/index.js\n' +
      '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)\n' +
      '    at Function.Module._load (internal/modules/cjs/loader.js:864:27)\n' +
      '    at Module.require (internal/modules/cjs/loader.js:1044:19)\n' +
      '    at require (internal/modules/cjs/helpers.js:77:18)\n' +
      '    at Object.<anonymous> (/Users/myuser/.npm/_npx/47867/lib/node_modules/snyk/src/lib/protect/update.js:7:11)\n' +
      '    at Module._compile (internal/modules/cjs/loader.js:1158:30)\n' +
      '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)\n' +
      '    at Module.load (internal/modules/cjs/loader.js:1002:32)\n' +
      '    at Function.Module._load (internal/modules/cjs/loader.js:901:14)\n' +
      '    at Module.require (internal/modules/cjs/loader.js:1044:19)',
    'error-code': 'MODULE_NOT_FOUND',
    command: 'wizard',
    integrationName: '',
    integrationVersion: ''
  },
  version: '1.316.0',
  os: 'macOS Catalina',
  nodeVersion: 'v12.16.1',
  id: '5af5613afc55bec18dd35c654ab0e24c3cfeea40',
  ci: false,
  durationMs: 139
} +0ms

  snyk Exit code: 2 +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 2570 +0ms
  snyk gzipped request body size: 593 +0ms
  snyk not using proxy +1ms

```

**Comment by joeholdcroft** [comment]
Hi @ffriedl89 ! Thanks for raising this, we're working on a fix right now :)
