### ISSUE TITLE
Snyk monitor undefined[🐛]

### ISSUE THREAD

**Issue by alterEgo123** [snyk/snyk#1128]
- `node -v`: v12.16.3
- `npm -v`: 3.5.2
- `snyk -v`: 1.323.0
- OS: Linux
- Command run: snyk monitor

### Expected behaviour
Get all known vulnerabilities for installed packages in python project.

### Actual behaviour
**Undefined** error.

### Steps to reproduce
sudo apt-install npm -y
sudo npm install -g n
sudo n latest
sudo npm install -g snyk
snyk auth **token**
snyk monitor 

### Debug log
undefined
    at monitor (/usr/local/lib/node_modules/snyk/src/cli/commands/monitor/index.ts:230:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  snyk analytics {
  args: [ { debug: true } ],
  command: 'bad-command',
  org: undefined,
  metadata: {
    pluginOptions: { debug: true },
    'error-message': '\n**PRIVATE_PATH**.\n\nundefined',
    error: 'Error: \n' +
      'Monitoring **PRIVATE_PATH**...\n' +
      '\n' +
      'undefined\n' +
      '    at monitor (/usr/local/lib/node_modules/snyk/src/cli/commands/monitor/index.ts:230:9)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
    'error-code': undefined,
    command: 'monitor',
    integrationName: '',
    integrationVersion: ''
  },
  version: '1.323.0',
  os: 'Linux 3.10',
  nodeVersion: 'v12.16.3',
  id: 'f32327a60ba480895e9c3921c53397002e8ac5ad',
  ci: false,
  durationMs: 116
} +0ms

  snyk Exit code: 2 +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 619 +0ms
  snyk gzipped request body size: 382 +0ms
  snyk not using proxy +0ms

**Comment by alterEgo123** [comment]
Apparently snyk monitor --command=python3 fixes it.
