### ISSUE TITLE
[🐛] `snyk auth` quits with non-zero exit code

### ISSUE THREAD

**Issue by adericbourg** [snyk/snyk#1187]
- `node -v`: v14.4.0
- `npm -v`: 6.14.4
- `snyk -v`: 1.339.3 (standalone)
- OS: macOS Catalina 10.15.5
- Command run: `snyk auth`

### Expected behaviour

`snyk auth` should authenticate CLI. 

### Actual behaviour

`snyk` CLI actually opens the browser but quits with non-zero exit code. 

### Steps to reproduce

Run `snyk auth -d`

My local network supports IPv6 but not my ISP.
Using an ISP supporting IPv6 allowed `snyk auth` to work.

### Debug log

```
$ snyk auth -d
  snyk auth { _: [], debug: true } +0ms

Now redirecting you to our auth page, go ahead and log in,
and once the auth is complete, return to this prompt and you'll
be ready to start using snyk.

If you can't wait use this url:
https://snyk.io/login?token=...

| Waiting...  snyk sending request to: https://snyk.io/api/v1/verify/callback +0ms
  snyk request body size: 48 +0ms
  snyk gzipped request body size: 66 +0ms
  snyk not using proxy +0ms
Error: connect EHOSTUNREACH 2a02:26f0:5c:487::ecd:443 - Local (:::58831)
    at internalConnect (net.js:964:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1110:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:70:10)
  snyk analytics { args: [],
  command: 'bad-command',
  org: undefined,
  metadata:
   { payloadSize: 48,
     gzippedPayloadSize: 66,
     'error-message': 'connect EHOSTUNREACH 2a02:26f0:5c:487::ecd:443 - Local (:::58831)',
     error: 'Error: connect EHOSTUNREACH 2a02:26f0:5c:487::ecd:443 - Local (:::58831)\n    at internalConnect (net.js:964:16)\n    at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)\n    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1110:9)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:70:10)',
     'error-code': 'EHOSTUNREACH',
     command: 'auth',
     integrationName: '',
     integrationVersion: '' },
  version: '1.339.3',
  os: 'macOS Catalina',
  nodeVersion: 'v8.16.2',
  standalone: true,
  id: 'e2798c7175af4d780695c0d77ce4f44c1e996e29',
  ci: false,
  durationMs: 3717 } +0ms

  snyk Exit code: 2 +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +49ms
  snyk request body size: 759 +0ms
  snyk gzipped request body size: 448 +0ms
  snyk not using proxy +0ms

$ echo $?
2
```

**Comment by dkontorovskyy** [comment]
Hey @adericbourg, can you check our latest release (v1.355.0), cos I'm sure it should have fixed your issue.
Here is a PR that fixed the issue
https://github.com/snyk/snyk/pull/1247

**Comment by adericbourg** [comment]
I updated Snyk CLI from v1.349.0 to v1.355.0: I confirm that it works now 👍
