### ISSUE TITLE
[🐛] 1.361.0 snyk commands failing with "Error: Cannot find module 'lodash'"

### ISSUE THREAD

**Issue by sndrsnk** [snyk/snyk#1261]
- `node -v`: v10.20.1
- `npm -v`: 6.14.4
- `snyk -v`: Unable to execute command, but the version is 1.361.0
- OS: OSX and Linux
- Command run: `snyk monitor` and just `snyk`

### Expected behaviour
Snyk command should be executed. 

### Actual behaviour
We receive the following error (same as the issue affecting `1.352.0`): 

```nohighlight
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/user/Projects/testing/snyk-test/node_modules/snyk-nodejs-lockfile-parser/lib/parsers/yarn2-lock-parse.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Steps to reproduce
Execute any snyk command. 

### Debug log
N/A

### Screenshots
N/A

**Comment by alfirin** [comment]
We have the same problem via the Azure pipeline...
And so our build failed...

```
2020-07-09T09:47:58.6628735Z [command]/usr/bin/sudo npm install -g snyk snyk-to-html
2020-07-09T09:48:25.6568525Z /usr/local/bin/snyk-to-html -> /usr/local/lib/node_modules/snyk-to-html/dist/index.js
2020-07-09T09:48:25.6624633Z /usr/local/bin/snyk -> /usr/local/lib/node_modules/snyk/dist/cli/index.js
2020-07-09T09:48:25.8640838Z + snyk-to-html@1.13.0
2020-07-09T09:48:25.8641701Z + snyk@1.361.0
2020-07-09T09:48:25.8642176Z added 544 packages from 386 contributors in 18.969s
2020-07-09T09:48:25.9556836Z 
2020-07-09T09:48:25.9603417Z [command]/usr/local/bin/snyk auth ***
2020-07-09T09:48:26.5133505Z Error: Cannot find module 'lodash'
2020-07-09T09:48:26.5136535Z Require stack:
2020-07-09T09:48:26.5137648Z - /usr/local/lib/node_modules/snyk/node_modules/snyk-nodejs-lockfile-parser/dist/parsers/yarn2-lock-parse.js
2020-07-09T09:48:26.5138280Z - /usr/local/lib/node_modules/snyk/node_modules/snyk-nodejs-lockfile-parser/dist/index.js
2020-07-09T09:48:26.5138852Z - /usr/local/lib/node_modules/snyk/dist/lib/plugins/nodejs-plugin/npm-lock-parser.js
2020-07-09T09:48:26.5139383Z - /usr/local/lib/node_modules/snyk/dist/lib/plugins/nodejs-plugin/index.js
2020-07-09T09:48:26.5139906Z - /usr/local/lib/node_modules/snyk/dist/lib/plugins/index.js
2020-07-09T09:48:26.5140414Z - /usr/local/lib/node_modules/snyk/dist/lib/plugins/get-single-plugin-result.js
2020-07-09T09:48:26.5140921Z - /usr/local/lib/node_modules/snyk/dist/lib/plugins/get-multi-plugin-result.js
2020-07-09T09:48:26.5141434Z - /usr/local/lib/node_modules/snyk/dist/lib/plugins/get-deps-from-plugin.js
2020-07-09T09:48:26.5141953Z - /usr/local/lib/node_modules/snyk/dist/lib/snyk-test/run-test.js
2020-07-09T09:48:26.5142429Z - /usr/local/lib/node_modules/snyk/dist/lib/snyk-test/index.js
2020-07-09T09:48:26.5142874Z - /usr/local/lib/node_modules/snyk/dist/lib/index.js
2020-07-09T09:48:26.5143476Z - /usr/local/lib/node_modules/snyk/dist/lib/analytics.js
2020-07-09T09:48:26.5144186Z - /usr/local/lib/node_modules/snyk/dist/cli/index.js
2020-07-09T09:48:26.5144557Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
2020-07-09T09:48:26.5145196Z     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
2020-07-09T09:48:26.5145567Z     at Module.require (internal/modules/cjs/loader.js:1026:19)
2020-07-09T09:48:26.5145914Z     at require (internal/modules/cjs/helpers.js:72:18)
2020-07-09T09:48:26.5146616Z     at Object.<anonymous> (/usr/local/lib/node_modules/snyk/node_modules/snyk-nodejs-lockfile-parser/lib/parsers/yarn2-lock-parse.ts:1:1)
2020-07-09T09:48:26.5147113Z     at Module._compile (internal/modules/cjs/loader.js:1138:30)
2020-07-09T09:48:26.5147665Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2020-07-09T09:48:26.5148029Z     at Module.load (internal/modules/cjs/loader.js:986:32)
2020-07-09T09:48:26.5148382Z     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2020-07-09T09:48:26.5148737Z     at Module.require (internal/modules/cjs/loader.js:1026:19)
2020-07-09T09:48:26.5200680Z 
2020-07-09T09:48:26.5231591Z 
2020-07-09T09:48:26.5232236Z 
2020-07-09T09:48:26.5232455Z ***************************
2020-07-09T09:48:26.5232694Z ** We have a problem! :( **
2020-07-09T09:48:26.5232928Z ***************************
2020-07-09T09:48:26.5233061Z 
2020-07-09T09:48:26.5233568Z Invalid token - Snyk does not authorized the user
2020-07-09T09:48:26.5275252Z ##[error]Invalid token - Snyk does not authorized the user
2020-07-09T09:48:26.5287264Z ##[section]Finishing: Running snyk tool
```

**Comment by gmc77** [comment]
Same on python with the latest python docker image `snyk/snyk-cli:python-3` Was ok yesterday. 

```
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/snyk/node_modules/snyk-nodejs-lockfile-parser/lib/parsers/yarn2-lock-parse.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

(also commented on https://github.com/snyk/snyk/issues/130#issuecomment-656039713)

**Comment by dgard1981** [comment]
I'm suffering the same issue as @alfirin - currently every single one of our Azure DevOps pipelines is broken because of Snyk.

This issue seems to be version `1.361.0` - everything was fine yesterday with version `1.360.0`.

**Comment by dgard1981** [comment]
Not sure if this is helpful - It seems that there has been several updates to `lodash` in the last 24 hours, and we've now had to include `lodash-core-4.17.15` in our package/lock files to get NPM packages that use `lodash` to run.

**Comment by alfirin** [comment]
I believe this is fixed from this commit: https://github.com/snyk/nodejs-lockfile-parser/commit/16b2636ee2ccf157eb6e81853ec46cc42fd38545

And this one: https://github.com/snyk/snyk/commit/915551b550e0fd14e02af65149da5d721c0a0bda

**Comment by dkontorovskyy** [comment]
@sndrsnk @alfirin @dgard1981 @gmc77, please update to the latest version of CLI (v1.361.3, https://github.com/snyk/snyk/releases/tag/v1.361.3) and issue should go away.
Sorry for inconvenience 🤗

**Comment by sndrsnk** [comment]
Thanks @dkontorovskyy, updating to v1.361.3 helped to remove the errors. Cheers!

**Comment by dgard1981** [comment]
@dkontorovskyy - Also working for me now, thanks.
