### ISSUE TITLE
[🐛] Internal error (reference: 576bb64b-584a-4f4d-a718-7cb2f12a0722)

### ISSUE THREAD

**Issue by Aeolun** [snyk/snyk#1264]
- OS: snyk/snyk-cli:1.263.0-npm (in gitlab runner)
- Command run:
```
$ snyk test --org=[something] --project-name=[something]
Internal error (reference: 576bb64b-584a-4f4d-a718-7cb2f12a0722)
```

### Expected behaviour
It should not give an internal error, or at least give a more helpful error.

### Actual behaviour
It gives an error with zero helpful steps to troubleshoot, every time we run the pipeline.

### Steps to reproduce
Unfortunately I cannot really reproduce our project here, please let me know if there's anything in specific that might help.

### Debug log
```
$ snyk test --org=japan --project-name=pr.git --debug
2020-07-10T08:38:49.450Z snyk test { _: [ [Circular] ],
  org: 'japan',
  'project-name': 'pr.git',
  debug: true }
2020-07-10T08:38:49.471Z snyk Analyzing npm dependencies for /builds/pr/package-lock.json
2020-07-10T08:38:50.009Z snyk policies found [ '/builds/pr' ]
2020-07-10T08:38:50.261Z snyk converting dep-tree to dep-graph { name: 'pr', targetFile: 'package-lock.json' }
2020-07-10T08:39:31.250Z snyk done converting dep-tree to dep-graph { uniquePkgsCount: 2040 }
2020-07-10T08:39:31.330Z snyk sending request to: https://snyk.io/api/v1/test-dep-graph
2020-07-10T08:39:31.330Z snyk request body size: 1664647
2020-07-10T08:39:31.330Z snyk gzipped request body size: 98226
2020-07-10T08:39:31.331Z snyk not using proxy
2020-07-10T08:39:39.110Z snyk Error running test { error:
   { InternalServerError: Internal server error
       at handleTestHttpErrorResponse (/usr/local/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:226:13)
       at request (/usr/local/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:205:21)
       at /usr/local/lib/node_modules/snyk/src/lib/request/index.ts:16:7
       at Generator.next (<anonymous>)
       at fulfilled (/usr/local/lib/node_modules/snyk/dist/lib/request/index.js:5:58)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'InternalServerError',
     code: 500,
     innerError: undefined,
     userMessage:
      'Internal error (reference: cb4ac4c6-5990-4f83-b69c-943a56a4cb2d)',
     strCode: 'INTERNAL_SERVER_ERROR' } }
2020-07-10T08:39:39.128Z snyk Failed to test 1 projects, errors:
2020-07-10T08:39:39.129Z snyk error: FailedToRunTestError: Internal error (reference: cb4ac4c6-5990-4f83-b69c-943a56a4cb2d)
    at /usr/local/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:184:11
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/snyk/dist/lib/snyk-test/run-test.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: 
Testing /builds/pr...
Internal error (reference: cb4ac4c6-5990-4f83-b69c-943a56a4cb2d)
    at /usr/local/lib/node_modules/snyk/src/cli/commands/test/index.ts:222:19
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/snyk/dist/cli/commands/test/index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-07-10T08:39:39.146Z snyk analytics { args:
   [ { org: 'japan',
       'project-name': '/pr.git',
       debug: true,
       showVulnPaths: 'some' } ],
  command: 'bad-command',
  org: 'japan',
  metadata:
   { local: [ true, true ],
     'generating-node-dependency-tree': { lockFile: true, targetFile: 'package-lock.json' },
     pluginName: 'snyk-nodejs-lockfile-parser',
     policies: 1,
     packageManager: 'npm',
     packageName: 'pr',
     packageVersion: '0.4.25',
     package: 'pr@0.4.25',
     depGraph: true,
     isDocker: false,
     payloadSize: 1664647,
     gzippedPayloadSize: 98226,
     'error-message':
      '\nTesting /builds/pr...\n\nInternal error (reference: cb4ac4c6-5990-4f83-b69c-943a56a4cb2d)',
     error:
      'Error: \nTesting /builds/pr...\n\nInternal error (reference: cb4ac4c6-5990-4f83-b69c-943a56a4cb2d)\n    at /usr/local/lib/node_modules/snyk/src/cli/commands/test/index.ts:222:19\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/local/lib/node_modules/snyk/dist/cli/commands/test/index.js:6:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     'error-code': 500,
     command: 'test' },
  version: '1.263.0',
  os: 'Linux 5.3',
  nodeVersion: 'v10.18.0',
  id: '63f6a1d3962c392bbd5fbb6cd69fa957432ab00e',
  ci: true,
  durationMs: 49714 }
2020-07-10T08:39:39.146Z snyk Exit code: 2
2020-07-10T08:39:39.147Z snyk sending request to: https://snyk.io/api/v1/analytics/cli
2020-07-10T08:39:39.147Z snyk request body size: 1177
2020-07-10T08:39:39.147Z snyk gzipped request body size: 633
2020-07-10T08:39:39.147Z snyk not using proxy
ERROR: Job failed: exit code 1
```

**Comment by pkey** [comment]
@Aeolun This is probably related to the outage that we had at around that time. Could you try running the test again?

**Comment by lili2311** [comment]
@Aeolun is this issue resolved for you?

**Comment by lili2311** [comment]
Closing this issue, please re-open if you need more help.

**Comment by intellix** [comment]
Also getting something similar:
```
? Add `snyk test` to package.json file to fail test on newly disclosed vulnerabilities?
This will require authentication via `snyk auth` when running tests. No
Applying updates using npm...
Saving .snyk policy file...
Updating package.json...
Analyzing npm dependencies for /Users/dominicwatson/Projects/api/package-lock.json
Remembering current dependencies for future notifications...
Internal error (reference: 364df545-9c5d-4e51-8600-1619fab20054)
```
