### ISSUE TITLE
Snyk install missing lodash

### ISSUE THREAD

**Issue by MPV** [snyk/snyk#130]
- `node -v`: v0.12.18
- `npm -v`: 2.15.11
- `snyk -v`: 1.69.5
- Command run: `snyk test`

### Expected behaviour
Snyk test working.

### Actual behaviour
`lodash` not found.

### Steps to reproduce

Install `snyk`:
```
$ npm install -g snyk
```

Run `snyk test`:
```
$ snyk test

module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/Cellar/asdf/0.4.1/installs/nodejs/0.12.18/.npm/lib/node_modules/snyk/cli/commands/test.js:9:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

```
$ snyk test --file build.sbt
/usr/local/Cellar/asdf/0.4.1/installs/nodejs/0.12.18/.npm/lib/node_modules/snyk/cli/index.js:11
if (args.options.file && args.options.file.match(/\.sln$/)) {
                                           ^
TypeError: undefined is not a function
    at Object.<anonymous> (/usr/local/Cellar/asdf/0.4.1/installs/nodejs/0.12.18/.npm/lib/node_modules/snyk/cli/index.js:11:44)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

```
$ snyk test --debug
  snyk test { _: [ [Circular] ], debug: true } +0ms
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/Cellar/asdf/0.4.1/installs/nodejs/0.12.18/.npm/lib/node_modules/snyk/cli/commands/test.js:9:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

```
$ snyk test --file build.sbt --debug
  snyk test { _: [ 'build.sbt', [Circular] ], file: true, debug: true } +0ms
/usr/local/Cellar/asdf/0.4.1/installs/nodejs/0.12.18/.npm/lib/node_modules/snyk/cli/index.js:11
if (args.options.file && args.options.file.match(/\.sln$/)) {
                                           ^
TypeError: undefined is not a function
    at Object.<anonymous> (/usr/local/Cellar/asdf/0.4.1/installs/nodejs/0.12.18/.npm/lib/node_modules/snyk/cli/index.js:11:44)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by joshje** [comment]
It seems that our custom lodash module isn't being loaded properly on npm `v2.15.11`. You will have more success with more recent versions of Node.js (or `npm`). Are you able to update to a later version of Node.js or npm?

If you are not able to update your version of node, then try updating `npm` to at least version 3 (`npm install -g npm@3`)

We will be phasing out support for Node.js `0.12` soon.

**Comment by adrukh** [comment]
@MPV this is now resolved (https://github.com/snyk/snyk/commit/a2ab4398), please upgrade to the latest release.

Reopen if we missed a spot!

**Comment by jakubigla** [comment]
I think after todays build, all docker images are broken with the above issue :(

**Comment by DalderupMaurice** [comment]
> I think after todays build, all docker images are broken with the above issue :(

I have something similar indeed. It says this when doing a yarn install:
```
 Unresolved node modules: @snyk/graphlib, @snyk/lodash
```

**Comment by dgard1981** [comment]
Version `1.360.0` worked fine yesterday, but today version `1.361.0` is broken.

This error is from the logs of an Azure DevOps pipeline run where we use the Snyk Security Scan task. However, the same behaviour has been noted when running `1.361.0` locally by multiple users.

Currently all of our Azure DevOps pipelines are broken because of Snyk.

```
/usr/local/bin/snyk auth ***
Error: Cannot find module 'lodash'
Require stack:
- /usr/local/lib/node_modules/snyk/node_modules/snyk-nodejs-lockfile-parser/dist/parsers/yarn2-lock-parse.js
- /usr/local/lib/node_modules/snyk/node_modules/snyk-nodejs-lockfile-parser/dist/index.js
- /usr/local/lib/node_modules/snyk/dist/lib/plugins/nodejs-plugin/npm-lock-parser.js
- /usr/local/lib/node_modules/snyk/dist/lib/plugins/nodejs-plugin/index.js
- /usr/local/lib/node_modules/snyk/dist/lib/plugins/index.js
- /usr/local/lib/node_modules/snyk/dist/lib/plugins/get-single-plugin-result.js
- /usr/local/lib/node_modules/snyk/dist/lib/plugins/get-multi-plugin-result.js
- /usr/local/lib/node_modules/snyk/dist/lib/plugins/get-deps-from-plugin.js
- /usr/local/lib/node_modules/snyk/dist/lib/snyk-test/run-test.js
- /usr/local/lib/node_modules/snyk/dist/lib/snyk-test/index.js
- /usr/local/lib/node_modules/snyk/dist/lib/index.js
- /usr/local/lib/node_modules/snyk/dist/lib/analytics.js
- /usr/local/lib/node_modules/snyk/dist/cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/node_modules/snyk-nodejs-lockfile-parser/lib/parsers/yarn2-lock-parse.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
```

**Comment by gmc77** [comment]
Getting similar issue with the latest python docker image `snyk/snyk-cli:python-3`

```
$ snyk test    --org=$SNYK_ORG --severity-threshold=$SCAN_THRESHOLD_PYTHON
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/snyk/node_modules/snyk-nodejs-lockfile-parser/lib/parsers/yarn2-lock-parse.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Was working ok yesterday

**Comment by jakubigla** [comment]
Let's face it. Snyk release process is a joke. Every few weeks they push broken images. 
What's more, they can do 5 releases a day because 4 of them didn't work. 

Also, you should always specify version when using docker images. Never use "latest"
