### ISSUE TITLE
[🐛] Converting circular structure to JSON

### ISSUE THREAD

**Issue by Drjacky** [snyk/snyk#1316]
- `node -v`: v14.7.0
- `npm -v`: 6.14.7
- `snyk -v`: 1.370.0 (standalone)
- OS: OSX macOS Catalina 10.15.6
- Command run: `snyk auth`

### Expected behaviour
Open a tab on the browser to authenticate

### Actual behaviour
```bash
➜  ~ snyk auth
Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_' -> object with constructor 'Array'
    --- index 0 closes the circle
```

### Steps to reproduce
I just run this: `brew tap snyk/tap && brew install sny`, then `snyk auth`, and I got the error. No tab opened!

### Debug log
```bash
➜  ~ snyk auth --debug
  snyk auth <ref *1> {
  _: [ [Circular *1] ],
  debug: true,
  callGraphBuilderTimeout: '300'
} +0ms
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_' -> object with constructor 'Array'
    --- index 0 closes the circle
    at JSON.stringify (<anonymous>)
    at /snapshot/snyk/dist/lib/request/request.js:24:31
    at new Promise (<anonymous>)
    at /snapshot/snyk/dist/lib/request/request.js:15:59
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)
    at internal/main/run_main_module.js:17:47
    at /snapshot/snyk/dist/lib/request/index.js:6:24
  snyk analytics {
  args: [ { debug: true, callGraphBuilderTimeout: '300' } ],
  command: 'bad-command',
  org: undefined,
  metadata: {
    'error-message': 'Converting circular structure to JSON\n' +
      "    --> starting at object with constructor 'Object'\n" +
      "    |     property '_' -> object with constructor 'Array'\n" +
      '    --- index 0 closes the circle',
    error: 'TypeError: Converting circular structure to JSON\n' +
      "    --> starting at object with constructor 'Object'\n" +
      "    |     property '_' -> object with constructor 'Array'\n" +
      '    --- index 0 closes the circle\n' +
      '    at JSON.stringify (<anonymous>)\n' +
      '    at /snapshot/snyk/dist/lib/request/request.js:24:31\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at /snapshot/snyk/dist/lib/request/request.js:15:59\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
      '    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)\n' +
      '    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)\n' +
      '    at internal/main/run_main_module.js:17:47\n' +
      '    at /snapshot/snyk/dist/lib/request/index.js:6:24',
    'error-code': undefined,
    command: 'auth'
  },
  version: '1.370.0',
  os: 'macOS Catalina',
  nodeVersion: 'v14.4.0',
  standalone: true,
  integrationName: '',
  integrationVersion: '',
  id: 'e9c76a6955a3959a430ff6dac3a6328ce8192af6',
  ci: false,
  durationMs: 14
} +0ms

  snyk Exit code: 2 +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1248 +0ms
  snyk gzipped request body size: 591 +1ms
  snyk not using proxy +0ms
```

### Screenshots
<img width="593" alt="Screen Shot 2020-08-08 at 20 27 06" src="https://user-images.githubusercontent.com/2296754/89717306-88768c80-d9b5-11ea-8810-66ca0e7a9e89.png">

**Comment by Drjacky** [comment]
I authenticated the machine with this command `snyk auth <your api token>` but, the actual problem still exists.

**Comment by JackuB** [comment]
@Drjacky hey, we had an issue earlier today with version 1.370.0 and we've released a [fixed](https://github.com/snyk/snyk/pull/1315) version [1.370.1](https://github.com/snyk/snyk/releases/tag/v1.370.1). If you upgrade, the issue should be fixed already.
