### ISSUE TITLE
snyk wizard Cannot read property 'allowed' of undefined

### ISSUE THREAD

**Issue by Ammonix** [snyk/snyk#133]
- `node -v`: `v8.4.0`
- `npm -v`: `5.3.0`
- `snyk -v`: `1.69.7`
- Command run: `snyk wizard --debug`

### Expected behaviour
wizard analyzes project

### Actual behaviour
`
 snyk wizard { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder D:\dev\<ProjectDir> +421ms
  snyk trying to autodetect for yarn.lock +0ms
  snyk trying to autodetect for package.json +0ms
  snyk checking for cli updates +0ms
  snyk ~~~~ LIVE RUN ~~~~ +79ms
  snyk add inline-auth false +375ms
  snyk add error-message Cannot read property 'allowed' of undefined +62ms
  snyk add error TypeError: Cannot read property 'allowed' of undefined
    at C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\cli\commands\protect\wizard.js:121:50
    at tryCatch (C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:410:12)
    at invokeCallback (C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:425:13)
    at publish (C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:393:7)
    at flush (C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) +0ms
  snyk add error-code undefined +0ms
  snyk add command wizard +0ms
TypeError: Cannot read property 'allowed' of undefined
    at C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\cli\commands\protect\wizard.js:121:50
    at tryCatch (C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:410:12)
    at invokeCallback (C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:425:13)
    at publish (C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:393:7)
    at flush (C:\Users\<User>\AppData\Roaming\npm\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  snyk { command: 'bad-command',
  snyk   args: [ { debug: true, packageManager: 'npm', newPolicy: true } ],
  snyk   metadata:
  snyk    { 'inline-auth': false,
  snyk      'error-message': 'Cannot read property \'allowed\' of undefined',
  snyk      error: 'TypeError: Cannot read property \'allowed\' of undefined\n    at C:\\Users\\<User>\\AppData\\Roaming\\npm\\node_modules\\snyk\\cli\\commands\\protect\\wizard.js:121:50\n    at tryCatch (C:\\Users\\<User>\\AppData\\Roaming\\npm\\node_modules\\snyk\\node_modules\\es6-promise\\dist\\es6-promise.js:410:12)\n    at invokeCallback (C:\\Users\\<User>\\AppData\\Roaming\\npm\\node_modules\\snyk\\node_modules\\es6-promise\\dist\\es6-promise.js:425:13)\n    at publish (C:\\Users\\<User>\\AppData\\Roaming\\npm\\node_modules\\snyk\\node_modules\\es6-promise\\dist\\es6-promise.js:393:7)\n    at flush (C:\\Users\\<User>\\AppData\\Roaming\\npm\\node_modules\\snyk\\node_modules\\es6-promise\\dist\\es6-promise.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
  snyk      'error-code': undefined,
  snyk      command: 'wizard' },
  snyk   version: '1.69.7',
  snyk   os: 'Windows 10',
  snyk   nodeVersion: 'v8.4.0',
  snyk   id: '<ID>',
  snyk   ci: false } +0ms
`

### Steps to reproduce

`npm install -g snyk`
`set http_proxy=<proxy>`
`set https_proxy=<proxy>`

---
I just cant get `snyk wizard` to work...

**Comment by darmalovan** [comment]
Hello, can you please provide the relevant logs from the proxy server ?

**Comment by adrukh** [comment]
@Ammonix we'd like to get to the bottom of this issue. Looking at the stack trace, the failure is coming from a failed request made to our server just before https://github.com/snyk/snyk/blob/master/cli/commands/protect/wizard.js#L121

There's no trace of an error on our end for this API endpoint, which makes me wonder how we can debug this as a network issue.

Please reach out to support@snyk.io so we can discuss this and come up with a solution.

**Comment by Ammonix** [comment]
@darmalovan and @adrukh 
Sorry for taking so long to respond to you guys.
So i was fiddling around with our proxy and it still doesn't work.
I think my company proxy is swallowing the request.
I will look in to the problem with our Firewall/Network Security Team.
Will keep you posted, until then, i will close the issue.

_short side note:
`snyk test` works just fine_
