### ISSUE TITLE
[🐛] Snyk test not working for Python setup.py

### ISSUE THREAD

**Issue by axsaucedo** [snyk/snyk#1367]
- `node -v`: v13.1.0
- `npm -v`: 6.12.1
- `snyk -v`: 1.384.0 (standalone)
- OS: (e.g. OSX, Linux, Windows, ...) Linux
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)

I tried the following commands:
* `snyk test --file=setup.py`
* `snyk test --file=setup.py --command=python3

### Expected behaviour

`snyk test` should work in python projects with setup.py.

### Actual behaviour

Snyk fails when running in setup.py (with the project outlined below) and the error "Failed to test pip project"

### Steps to reproduce
You can reproduce by running `snyk test --file=setup.py` in this setup.py file: https://github.com/SeldonIO/seldon-core/blob/master/python/setup.py

### Debug log
Output of debug flag:
```
  snyk test {
  _: [ [Circular] ],
  file: 'setup.py',
  debug: true,
  callGraphBuilderTimeout: '300'
} +0ms
  snyk:run-test Error running test {
  error: 'Traceback (most recent call last):\n' +
    '  File "/tmp/tmp-15799TiVMWyREzc1T/pip_resolve.py", line 314, in <module>\n' +
    '    sys.exit(main())\n' +
    '  File "/tmp/tmp-15799TiVMWyREzc1T/pip_resolve.py", line 310, in main\n' +
    '    only_provenance=args.only_provenance,\n' +
    '  File "/tmp/tmp-15799TiVMWyREzc1T/pip_resolve.py", line 256, in create_dependencies_tree_by_req_file_path\n' +
    '    required = get_requirements_list(requirements_file_path, dev_deps=dev_deps)\n' +
    '  File "/tmp/tmp-15799TiVMWyREzc1T/pip_resolve.py", line 210, in get_requirements_list\n' +
    '    requirements_data = setup_file.parse_requirements(setup_py_file_content)\n' +
    '  File "/tmp/tmp-15799TiVMWyREzc1T/setup_file.py", line 36, in parse_requirements\n' +
    '    passed_arguments = parse(setup_py_content)\n' +
    '  File "/tmp/tmp-15799TiVMWyREzc1T/setup_file.py", line 16, in parse\n' +
    '    exec(setup_py_content, globals())\n' +
    '  File "<string>", line 7, in <module>\n' +
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp-15799TiVMWyREzc1T/seldon_core/version.py'\n"
} +0ms
  snyk-test Failed to test 1 projects, errors: +0ms
  snyk-test error: FailedToRunTestError: Failed to test pip project
    at runTest (/snapshot/snyk/dist/lib/snyk-test/run-test.js:100:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) +2ms
Error:
Testing /home/alejandro/Programming/kubernetes/seldon/seldon-core/python...

Failed to test pip project
    at test (/snapshot/snyk/dist/cli/commands/test/index.js:200:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  snyk analytics {
  args: [
    {
      file: 'setup.py',
      debug: true,
      callGraphBuilderTimeout: '300',
      org: undefined,
      showVulnPaths: 'some'
    }
  ],
  command: 'bad-command',
  org: undefined,
  metadata: {
    local: true,
    'error-message': '\n' +
      'Testing /home/alejandro/Programming/kubernetes/seldon/seldon-core/python...\n' +
      '\n' +
      'Failed to test pip project',
    error: 'Error: \n' +
      'Testing /home/alejandro/Programming/kubernetes/seldon/seldon-core/python...\n' +
      '\n' +
      'Failed to test pip project\n' +
      '    at test (/snapshot/snyk/dist/cli/commands/test/index.js:200:23)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
    'error-code': 500,
    command: 'test'
  },
  version: '1.384.0',
  os: 'Linux 4.4',
  nodeVersion: 'v12.18.1',
  standalone: true,
  integrationName: '',
  integrationVersion: '',
  id: '53151900b95aae3c3d491e570ae3e4feecfce669',
  ci: false,
  durationMs: 1875
} +0ms

  snyk Exit code: 2 +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 786 +0ms
  snyk gzipped request body size: 459 +0ms
  snyk not using proxy +0ms
```

**Comment by axsaucedo** [comment]
I can confirm this fails in multiple environments (we run it in our CI and the same failure appears) - ie https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2325/6.log

**Comment by axsaucedo** [comment]
This was due to the setup.py file opening a file from relative folder, it was addressed by removing this function from the setup.py
