### ISSUE TITLE
Re-install remediation option failed - unknown error was encountered

### ISSUE THREAD

**Issue by callmeaponte** [snyk/snyk#140]
- `node -v`: 8.9.4
- `npm -v`: 5.7.1
- `snyk -v`: 1.70.3
- Command run: `snyk wizard`

### Expected behaviour
Expected re-install to work properly.

### Actual behaviour
The re-install failed and my **email-templates** dependency was deleted.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

```
Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

? Do you want to revisit your existing policy [y] or only update it [N]? Yes
Querying vulnerabilities database...
Tested 939 dependencies for known vulnerabilities, found 4 vulnerabilities, 13 vulnerable paths.

? Low severity vuln found in clean-css@3.4.28, introduced via email-templates@3.5.0
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:clean-css:20180306
- from: email-templates@3.5.0 > preview-email@0.0.7 > pug@2.0.0 > pug-filters@3.0.0 > clean-css@3.4.28
  Remediation options Re-install email-templates@3.5.0

? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-build@2.2.0 > decompress@3.0.0 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromatch@2.3.11 > braces@1.8.5
  Remediation options Patch (none available)

? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-build@2.2.0 > download@4.4.3 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromatch@2.3.11 > braces@1.8.5
  Remediation options Patch (none available)

? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-build@2.2.0 > download@4.4.3 > gulp-decompress@1.2.0 > decompress@3.0.0 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromat
ch@2.3.11 > braces@1.8.5
  Remediation options Patch (none available)

? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-wrapper@3.0.2 > download@4.4.3 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromatch@2.3.11 > braces@1.8.5
  Remediation options Patch (none available)

? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-wrapper@3.0.2 > download@4.4.3 > gulp-decompress@1.2.0 > decompress@3.0.0 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > microm
atch@2.3.11 > braces@1.8.5
  Remediation options Patch (none available)

? Low severity vuln found in braces@1.8.5, introduced via imagemin-pngquant@5.1.0
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-pngquant@5.1.0 > pngquant-bin@4.0.0 > bin-wrapper@3.0.2 > download@4.4.3 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromatch@2.3.11 > braces@1.8.5
  Remediation options Patch (none available)

? Low severity vuln found in braces@1.8.5, introduced via imagemin-pngquant@5.1.0
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-pngquant@5.1.0 > pngquant-bin@4.0.0 > bin-wrapper@3.0.2 > download@4.4.3 > gulp-decompress@1.2.0 > decompress@3.0.0 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > microm
atch@2.3.11 > braces@1.8.5
  Remediation options Patch (none available)

? High severity vuln found in shelljs@0.7.8, introduced via shelljs@0.7.8
- desc: Command Injection
- info: https://snyk.io/vuln/npm:shelljs:20140723
  Remediation options Patch (none available)

? High severity vuln found in shelljs@0.7.8, introduced via yeoman-generator@1.1.1
- desc: Command Injection
- info: https://snyk.io/vuln/npm:shelljs:20140723
- from: yeoman-generator@1.1.1 > shelljs@0.7.8
  Remediation options Patch (none available)

? Medium severity vuln found in tunnel-agent@0.4.3, introduced via imagemin-jpegtran@5.0.2
- desc: Uninitialized Memory Exposure
- info: https://snyk.io/vuln/npm:tunnel-agent:20170305
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-build@2.2.0 > download@4.4.3 > caw@1.2.0 > tunnel-agent@0.4.3
  Remediation options Patch (none available)

? Medium severity vuln found in tunnel-agent@0.4.3, introduced via imagemin-jpegtran@5.0.2
- desc: Uninitialized Memory Exposure
- info: https://snyk.io/vuln/npm:tunnel-agent:20170305
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-wrapper@3.0.2 > download@4.4.3 > caw@1.2.0 > tunnel-agent@0.4.3
  Remediation options Patch (none available)

? Medium severity vuln found in tunnel-agent@0.4.3, introduced via imagemin-pngquant@5.1.0
- desc: Uninitialized Memory Exposure
- info: https://snyk.io/vuln/npm:tunnel-agent:20170305
- from: imagemin-pngquant@5.1.0 > pngquant-bin@4.0.0 > bin-wrapper@3.0.2 > download@4.4.3 > caw@1.2.0 > tunnel-agent@0.4.3
  Remediation options Patch (none available)
Applying updates using npm...
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: Command failed: npm install --save email-templates@3.5.0
(node:9694) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9693) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9693) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9697) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9692) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9693) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9695) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9697) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9696) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9695) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9692) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
(node:9692) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:9691) Warning: a promise was created in a handler at /Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:39:25 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/andrewaponte/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.

npm ERR! cancel after 1 retries!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrewaponte/.npm/_logs/2018-03-23T01_35_17_956Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Saving .snyk policy file...
Updating package.json...
Remembering current dependencies for future notifications...

Your .snyk policy file has been successfully updated.
To review your policy, run `snyk policy`.

You can see a snapshot of your dependencies here:
https://snyk.io/org/callmeaponte/monitor/849f886b-e10f-4d25-b99c-d322816e0aa5

We'll notify you when relevant new vulnerabilities are disclosed.
```

---

Unfortunately I didn't run `snyk wizard` with the --debug flag (assuming it has one), and running it again won't reproduce the error as I've already manually reinstalled `email-templates`.

If you guys need any more information or would like to see the contents of the npm debug log, just let me know and I'll be happy to provide it.

**Comment by jmcdo29** [comment]
I'm having a similar issue, however, I cannot get snyk wizard to run after choosing the re-install option. 
```snyk wizard --debug
  snyk wizard { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder C:\Users\jay.mcdoniel\Documents\Angular_Tutorials\angular-zeldaplay +0ms
  snyk found package file package.json in C:\Users\jay.mcdoniel\Documents\Angular_Tutorials\angular-zeldaplay +1ms
  snyk ~~~~ LIVE RUN ~~~~ +0ms
  snyk sending request to: https://snyk.io/api/v1/verify/token +0ms
  snyk request body size: 46 +0ms
  snyk gzipped request body size: 66 +1ms
  snyk analytics add payloadSize 46 +0ms
  snyk analytics add gzippedPayloadSize 66 +1ms
  snyk not using proxy +3ms
  snyk analytics add inline-auth false +959ms
  snyk not using proxy +963ms

Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

  snyk analytics add local true +674ms
  snyk policies found [ 'C:\\Users\\jay.mcdoniel\\Documents\\Angular_Tutorials\\angular-zeldaplay' ] +0ms
  snyk analytics add policies 1 +29s
Analyzing npm dependencies for package.json
  snyk analytics add packageManager npm +2ms
  snyk analytics add packageName zelda-play +1ms
  snyk analytics add packageVersion 0.0.0 +0ms
  snyk analytics add package zelda-play@0.0.0 +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm +30s
  snyk request body size: 821508 +1ms
  snyk gzipped request body size: 32879 +0ms
  snyk analytics add payloadSize 821508 +21ms
  snyk analytics add gzippedPayloadSize 32879 +0ms
  snyk not using proxy +1ms
  snyk analytics add vulns-pre-policy 2 +2s
  snyk analytics add vulns 2 +4ms
Querying vulnerabilities database...
Tested 278 dependencies for known vulnerabilities, found 1 vulnerabilities, 2 vulnerable paths.
  snyk starting questions +33s
  snyk getUpdatePrompts +0ms

  snyk final show npm:extend:20180424 when true +9ms
? Low severity vuln found in extend@3.0.1, introduced via knex@0.15.2
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:extend:20180424
- from: knex@0.15.2 > liftoff@2.5.0 > extend@3.0.1
  Remediation options Re-install knex@0.15.2

  snyk final show npm:extend:20180424 when true +15s
? Low severity vuln found in extend@3.0.1, introduced via objection@1.2.0
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:extend:20180424
- from: objection@1.2.0 > knex@0.15.2 > liftoff@2.5.0 > extend@3.0.1
  Remediation options Re-install objection@1.2.0
  snyk getPatchPrompts +2s
  snyk getIgnorePrompts +1ms
```
---
After this is just hangs and does nothing. Control-C and Control-Z both are unresponsive and to exit I have to kill the terminal. This happens in both git-bash and windows command prompt.

**Comment by lili2311** [comment]
Hi! I am currently looking at an issue that seems related to yours, I will keep you posted over the next few days with my progress.

Would you be able to share the package.json so I can replicate this issue locally? It also seems like you may have a snyk policy file '.snyk' could you share this as well? If you prefer you can send them to support@snyk.io. thanks!

**Comment by jmcdo29** [comment]
Certainly! Here is the package.json file

```
{
  "name": "zelda-play",
  "version": "0.0.0",
  "license": "MIT",
  "engines": {
    "npm": "6.x"
  },
  "scripts": {
    "ng": "ng",
    "start": "node server/server.js",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "heroku-postbuild": "npm run build"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.9",
    "@angular/common": "^6.0.9",
    "@angular/compiler": "^6.0.9",
    "@angular/core": "^6.0.9",
    "@angular/forms": "^6.0.9",
    "@angular/http": "^6.0.9",
    "@angular/platform-browser": "^6.0.9",
    "@angular/platform-browser-dynamic": "^6.0.9",
    "@angular/router": "^6.0.9",
    "angular-in-memory-web-api": "^0.6.0",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.18.3",
    "connect-session-knex": "^1.4.0",
    "core-js": "^2.5.7",
    "cors": "^2.8.4",
    "dotenv": "^6.0.0",
    "express": "^4.16.3",
    "express-flash": "0.0.2",
    "express-session": "^1.15.6",
    "file-saver": "^1.3.8",
    "helmet": "^3.12.1",
    "knex": "^0.15.2",
    "morgan": "^1.9.0",
    "objection": "^1.2.0",
    "path": "^0.12.7",
    "pg": "^7.4.3",
    "rxjs": "^6.2.1",
    "typescript": "^2.7.2",
    "url": "^0.11.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.9",
    "@angular/language-service": "^6.0.9",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.2",
    "@types/file-saver": "^1.3.0",
    "@types/node": "^10.5.2",
    "codelyzer": "^4.4.2",
    "jasmine-core": "^3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.1",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^1.2.0",
    "protractor": "^5.3.2",
    "ts-node": "^7.0.0",
    "tslint": "^5.10.0"
  }
}
```

At one point I had a .snyk file but the configurations in it were empty so I deleted it to try and run from a clean slate. The two packages that are causing the issues are `knex: ^0.15.2` and `objection: ^1.2.0`. Thanks again for your help!

**Comment by lili2311** [comment]
Great thanks! I will try to replicate locally. 
Can you confirm you have already tried deleting your `node_modules` and re-installing to ensure a clean slate before running wizard again?

**Comment by jmcdo29** [comment]
Is there any update on this? I've updated to the latest version of snyk (I think it was 1.90.2), but I'm still seeing the same issue.

**Comment by jmcdo29** [comment]
I was able to get snyk wizard working yesterday. I had some issues with my npm install so I did a fresh install of Node and npm. Figured I'd give it a shot to run snyk wizard and got a .snyk file out of it. Snyk version 1.94.0, npm version 6.4.1, Node version 10.9.0. Hopefully this helps everyone who had the same problem!
