### ISSUE TITLE
[🐛]

### ISSUE THREAD

**Issue by PRIYANKA111999** [snyk/snyk#1496]
- `node -v`: v6.17.1
- `npm -v`:  3.10.10
- `snyk -v`: 
- OS: centos7

 $ snyk --version

/usr/lib/node_modules/snyk/dist/cli/index.js:33
async function runCommand(args) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

 $ snyk auth

/usr/lib/node_modules/snyk/dist/cli/index.js:33
async function runCommand(args) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by JackuB** [comment]
Hi @PRIYANKA111999 Node.js v6 is no longer supported - I'd recommend to update at least Node v10 or v12 if possible.

https://github.com/snyk/snyk/blob/10396d1a7fff270995c3171f83b1477fa5b7f2a5/package.json#L19-L21
