### ISSUE TITLE
413 With large dependency tree

### ISSUE THREAD

**Issue by barlock** [snyk/snyk#156]
- `node -v`: v8.9.4
- `npm -v`: 5.6.0
- `snyk -v`: 1.80.0
- Command run: yarn snyk test --dev

### Expected behaviour
Runs to completion

### Actual behaviour
Command failed. 413 

### Notes
I have a large dependency tree, ~700mb node_modules dir. I can't really shrink this and honestly I haven't done anything interesting here. I'm assuming that https://snyk.io/api/v1/vuln/npm has a max payload size? (69MB being sent) I couldn't locate the docs for this particular api call, I'm not sure if this can be sent in chunks to keep the size low. 

---

```
  snyk test { _: [ [Circular] ], dev: true } +0ms
  snyk no file specified. Trying to autodetect in base folder /Users/michael/workspace/lifeomic/jupiter-web-galaxy +0ms
  snyk trying to autodetect for yarn.lock +0ms
  snyk analytics add local true +0ms
  snyk policies found [ '/Users/michael/workspace/lifeomic/jupiter-web-galaxy',
  '/Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/@lifeomic/abac',
  '/Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/@lifeomic/alpha',
  '/Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/@lifeomic/fhir-schemas',
  '/Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/@lifeomic/platform-headers',
  '/Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/@lifeomic/usage-stream',
  '/Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/@lifeomic/dev-tools',
  '/Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/@lifeomic/jupiter-web-toolkit',
  '/Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/@lifeomic/lambda-tools' ] +0ms
  snyk analytics add policies 9 +25s
  snyk analytics add packageManager npm +37ms
  snyk analytics add packageName jupiter-web-galaxy +0ms
  snyk analytics add packageVersion 0.1.0 +0ms
  snyk analytics add package jupiter-web-galaxy@0.1.0 +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm +0ms
  snyk request body size: 69964780 +1ms
  snyk analytics add payloadSize 69964780 +883ms
  snyk not using proxy +0ms
  snyk analytics add error-message 413 +783ms
  snyk analytics add error Error: 413
    at /Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/snyk/cli/commands/test.js:134:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) +0ms
  snyk analytics add error-code 413 +0ms
  snyk analytics add command test +0ms
An unknown error occurred. Please include the trace below when reporting to Snyk:
Error: 413
    at /Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/snyk/cli/commands/test.js:134:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  snyk analytics { command: 'bad-command',
  args: [ { dev: true, org: undefined, showVulnPaths: true } ],
  metadata:
   { local: true,
     policies: 9,
     packageManager: 'npm',
     packageName: 'jupiter-web-galaxy',
     packageVersion: '0.1.0',
     package: 'jupiter-web-galaxy@0.1.0',
     payloadSize: 69964780,
     'error-message': '413',
     error: 'Error: 413\n    at /Users/michael/workspace/lifeomic/jupiter-web-galaxy/node_modules/snyk/cli/commands/test.js:134:21\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
     'error-code': 413,
     command: 'test' },
  version: '1.80.0',
  os: 'macOS High Sierra',
  nodeVersion: 'v8.9.4',
  id: '56a63e49170ce265c51815774579ae18f9ca9e84',
  ci: false,
  durationMs: 26848 } +2ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +786ms
  snyk request body size: 676 +0ms
  snyk not using proxy +0ms

**Comment by michael-go** [comment]
Hi @barlock, thanks for reporting this!

We indeed have a 50MB threshold on the payload size.

We are working now on an improvement in our backed to handle such bigger dep trees and once it's merged - we will increase the threshold, supporting your project. Later we also plan to improve the way we represent the dep trees, drastically reducing the payload size.

We will update you once you should try again.

Thank you and sorry for the inconvenience 🙇 🙏

**Comment by m-handy** [comment]
Hi @michael-go 
I would ask how it looks with increasing paylod size, because I'm facing similar issue with maven and `payloadSize: 623695`. Thanks :)

**Comment by adrukh** [comment]
@barlock we extended the max payload size to 150MB, and made some improvements to the CLI to be more robust with regards to large payloads. Can you try on the latest version (1.89.0 right now) and see if the issue persists?

**Comment by barlock** [comment]
Cc @travomic

**Comment by adrukh** [comment]
A bunch of additional performance improvements went live this week, please upgrade to the latest cli version and comment here if you're not getting the expected results!

Thanks for bearing with us :)

**Comment by tierra** [comment]
Latest update dropped payload size on one of my more troublesome projects from:

```
  snyk request body size: 364914771 +1ms
  snyk gzipped request body size: 5778806 +0ms
```

to:

```
  snyk request body size: 236854135 +1ms
  snyk gzipped request body size: 3489928 +0ms
```

Definitely a significant improvement, thanks!

I think I've got other stuff on my project to fix that's causing the bulk of problems here that should get me back into a working payload size.

**Comment by adrukh** [comment]
@tierra thanks for the update! We're working on further improvements in this area, and your case is quite extreme... :) Can you please share your project's lockfile (npm or yarn), here or over support@snyk.io? It will help us validate our progress against real life conditions such as this one.

**Comment by lili2311** [comment]
👋@tierra I wanted to add here that if you are using `package-lock.json` we have now released support for it, one of the improvements is that it generates much smaller output. This may help your issue.

To give it a try get the lates version of the snyk cli and run `snyk test --file=path/to/package-lock.json`

**Comment by tierra** [comment]
That's great news! Some of my projects are still using Yarn, but a few have switched back to `npm@6` that will benefit immensely from that! Looking forward to putting aside some time to try it out.

**Comment by lili2311** [comment]
👋 Is this still an issue for you?

**Comment by tierra** [comment]
Hi @lili2311, we're still above that package payload size for the API at the moment. I tested one more time this morning with the latest NPM snyk version. I've sent over my package.json and yarn.lock, along with the debug output I'm seeing to support@snyk.io so you can inspect it further, and potentially work on more fixes that could allow these unconventionally large dependency trees.

**Comment by lili2311** [comment]
We have made further changes you can test out this flag which can help reduce the size even further https://github.com/snyk/snyk/blob/master/help/help.txt#L55

We are still working on system wide updates to handle larger projects and will continue to do so over the next few months, so keep an eye out for more updates.

Is the issue still with `snyk test` or `snyk monitor`?

**Comment by lili2311** [comment]
@tierra do you have a support case number to share with me?

**Comment by tierra** [comment]
I did get a reply from Unnur back when I sent it, confirming it was received, but didn't get any case number for it.

We're still using Yarn on this project in particular, but might be able to switch that to NPM@6 at some point near term. When using yarn.lock, I'm still getting payload size problems, even with 1.186.0:

```
$ node --max-old-space-size=4096 ~/.yarn/bin/snyk monitor --project-name=project:node --debug
  snyk monitor { _: [ [Circular] ],
  'project-name': 'project:node',
  debug: true } +0ms
  snyk Analyzing npm dependencies for /home/bpetty/project/yarn.lock +0ms
  snyk sending request to: https://snyk.io/api/v1/monitor/yarn +0ms
  snyk request body size: 402711985 +0ms
  snyk gzipped request body size: 3958830 +0ms
  snyk not using proxy +3ms
Error: 
Monitoring /home/bpetty/project...

Server returned unexpected error for the monitor request. Status code: 413
    at /home/bpetty/.config/yarn/global/node_modules/snyk/src/cli/commands/monitor.ts:235:9
    at Generator.throw (<anonymous>)
    at rejected (/home/bpetty/.config/yarn/global/node_modules/snyk/dist/cli/commands/monitor.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  snyk analytics { args: [ { 'project-name': 'project:node', debug: true } ],
  command: 'bad-command',
  metadata:
   { packageManager: [ 'yarn', 'yarn' ],
     pluginOptions: {},
     local: true,
     'generating-node-dependency-tree': { lockFile: true, targetFile: 'yarn.lock' },
     isDocker: false,
     targetBranch: 'master',
     payloadSize: 402711985,
     gzippedPayloadSize: 3958830,
     'error-message':
      '\nMonitoring /home/bpetty/project...\n\nServer returned unexpected error for the monitor request. Status code: 413',
     error:
      'Error: \nMonitoring /home/bpetty/project...\n\nServer returned unexpected error for the monitor request. Status code: 413\n    at /home/bpetty/.config/yarn/global/node_modules/snyk/src/cli/commands/monitor.ts:235:9\n    at Generator.throw (<anonymous>)\n    at rejected (/home/bpetty/.config/yarn/global/node_modules/snyk/dist/cli/commands/monitor.js:5:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     'error-code': undefined,
     command: 'monitor' },
  version: '1.186.0',
  os: 'Linux 5.0',
  nodeVersion: 'v10.15.2',
  id: 'f4f31e5697e2496f43d92ec0dd19547f4b605af2',
  ci: false,
  durationMs: 24993 } +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +8s
  snyk request body size: 1167 +0ms
  snyk gzipped request body size: 608 +0ms
  snyk not using proxy +0ms

  snyk Exit code: 2 +0ms
```

I've used NPM to generate a `package-lock.json`, just to see what that's looking like right now, but it seems like the payload is even bigger, not smaller, and I still certainly see a 413 response:

```
  snyk Analyzing npm dependencies for /home/bpetty/project/package-lock.json +0ms
  snyk sending request to: https://snyk.io/api/v1/monitor/npm +0ms
  snyk request body size: 770738803 +0ms
  snyk gzipped request body size: 10298444 +0ms
```

**Comment by lili2311** [comment]
hi @tierra! Is the issue still occurring for you?  We have released many improvements since last we spoke. If the issue persists please email support@snyk.io with the example yarn.lock & package.json so we can replicate this on our end.

I would also recommend trying with `--prune-repeated-sub-dependencies`

**Comment by lili2311** [comment]
hi @tierra I am closing this issue due to inactivity. Please re-open this issue if it is still happening.
