### ISSUE TITLE
[🐛] snyk auth fails with `missing auth token`

### ISSUE THREAD

**Issue by iartarisi** [snyk/snyk#1569]
- `node -v`: v10.19.0
- `npm -v`: 6.13.4
- `snyk -v`: 1.437.0
- OS: Alpine 3.10 inside docker
- Command run: `snyk auth`

### Expected behaviour
`SNYK_TOKEN=$SNYK_TOKEN snyk auth` should work. As well as `snyk auth` when `SNYK_TOKEN` was set in the environment

### Actual behaviour
```
bash-5.0# SNYK_TOKEN=$SNYK_TOKEN snyk auth
Snyk is missing auth token in order to run inside CI. You must include your API token as an environment value: `SNYK_TOKEN=12345678`

bash-5.0# snyk auth $SNYK_TOKEN

Your account has been authenticated. Snyk is now ready to be used.
```

### Debug log
```
# snyk auth --debug
  snyk auth { _: [], debug: true, callGraphBuilderTimeout: '300' } +0ms
  snyk auth { _: [], debug: true, callGraphBuilderTimeout: '300' } +0ms
CustomError: Snyk is missing auth token in order to run inside CI. You must include your API token as an environment value: `SNYK_TOKEN=12345678`
    at Object.MisconfiguredAuthInCI (/usr/lib/node_modules/snyk/src/lib/errors/misconfigured-auth-in-ci-error.ts:8:17)
    at webAuth (/usr/lib/node_modules/snyk/src/cli/commands/auth/index.ts:64:27)
    at auth (/usr/lib/node_modules/snyk/src/cli/commands/auth/index.ts:140:15)
    at Object.method (/usr/lib/node_modules/snyk/src/lib/hotload.js:15:14)
    at runCommand (/usr/lib/node_modules/snyk/src/cli/index.ts:53:36)
    at main (/usr/lib/node_modules/snyk/src/cli/index.ts:298:17)
    at Object.<anonymous> (/usr/lib/node_modules/snyk/src/cli/index.ts:319:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

  snyk Exit code: 2 +0ms
  snyk analytics { args: [],
  command: 'bad-command',
  org: undefined,
  metadata:
   { 'error-message':
      'Snyk is missing auth token in order to run inside CI. You must include your API token as an environment value: `SNYK_TOKEN=12345678`',
     error:
      'CustomError: Snyk is missing auth token in order to run inside CI. You must include your API token as an environment value: `SNYK_TOKEN=12345678`\n    at Object.MisconfiguredAuthInCI (/usr/lib/node_modules/snyk/src/lib/errors/misconfigured-auth-in-ci-error.ts:8:17)\n    at webAuth (/usr/lib/node_modules/snyk/src/cli/commands/auth/index.ts:64:27)\n    at auth (/usr/lib/node_modules/snyk/src/cli/commands/auth/index.ts:140:15)\n    at Object.method (/usr/lib/node_modules/snyk/src/lib/hotload.js:15:14)\n    at runCommand (/usr/lib/node_modules/snyk/src/cli/index.ts:53:36)\n    at main (/usr/lib/node_modules/snyk/src/cli/index.ts:298:17)\n    at Object.<anonymous> (/usr/lib/node_modules/snyk/src/cli/index.ts:319:13)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)',
     'error-code': 401,
     command: 'auth' },
  version: '1.437.0',
  os: 'Linux 4.15',
  nodeVersion: 'v10.19.0',
  standalone: false,
  integrationName: '',
  integrationVersion: '',
  integrationEnvironment: '',
  integrationEnvironmentVersion: '',
  id: '694bf63a4d3ce317bd10b4e11d55ffc0b9d9de37',
  ci: true,
  environment: { npmVersion: '6.13.4' },
  durationMs: 269,
  metrics:
   { network_time: { type: 'timer', values: [], total: 0 },
     cpu_time: { type: 'synthetic', values: [Array], total: 269 } } } +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1603 +0ms
  snyk gzipped request body size: 667 +0ms
  snyk not using proxy +1ms
```

**Comment by iartarisi** [comment]
Removing the package cache like suggested in this ticket works: https://github.com/snyk/snyk/issues/1505 

So I'll close this ticket in favour of that one.
