### ISSUE TITLE
[🐛] Test with Snyk token without permissions for organization gives non-describtive error message

### ISSUE THREAD

**Issue by Crevil** [snyk/snyk#1625]
- `node -v`: v12.20.1
- `npm -v`: 6.14.10
- `snyk -v`: 1.448.0
- OS: (e.g. OSX, Linux, Windows, ...)
- Command run: `SNYK_TOKEN=valid-for-other-org snyk test --org="no-perm"`

### Expected behaviour

An error message indicating that the token is not valid for the provided organization.

### Actual behaviour

The command fails with exit code `2` and the following message.

```
$ snyk test --org="no-perm"
Couldn't find the requested package
```

### Steps to reproduce

```
# create an API token for organization 1.
$ export SNYK_TOKEN=<uuid>
$ snyk test --org="another-org"
```

### Debug log

<details>
<summary>Debug log</summary>

```
snyk test --debug --org="non-perm-org" --project-name="project-name:docker" --file="Dockerfile" --json-file-output="reports/snyk-docker.json" --docker project-image-registry:test
  snyk test {
  _: [ 'project-image-registry:test', [Circular] ],
  debug: true,
  org: 'non-perm-org',
  'project-name': 'project-name:docker',
  file: 'Dockerfile',
  'json-file-output': 'reports/snyk-docker.json',
  docker: true,
  callGraphBuilderTimeout: '300'
} +0ms
  snyk Docker.save: targetImage: project-image-registry:test, destination: /var/folders/c0/c625rq0j5vxcps_n4pcpgl6r0000gn/T/tmp-61490-xaQSoKzXUQ8a/126cd897-e23c-4400-a2d1-d20a91091a53/image.tar +0ms
  snyk Potential policy locations found: [] +0msproject-name:test/Dockerfile
  snyk sending request to: https://snyk.io/api/v1/test-dependencies +0ms
  snyk request body size: 9308 +0ms
  snyk gzipped request body size: 1982 +0ms
  snyk not using proxy +1ms
  snyk Can't remove folder /var/folders/c0/c625rq0j5vxcps_n4pcpgl6r0000gn/T/tmp-61490-xaQSoKzXUQ8a/126cd897-e23c-4400-a2d1-d20a91091a53, got error null +0ms
  snyk:run-test Error running test {..
  error: NonExistingPackageError: Couldn't find the requested package
      at handleTestHttpErrorResponse (/Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:491:13)
      at /Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:470:21
      at module.exports (/Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/snyk/src/lib/request/index.ts:20:7)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    code: 404,
    innerError: undefined,
    userMessage: "Couldn't find the requested package"
  }
} +0ms
  snyk-test Failed to test 1 projects, errors: +0ms
  snyk-test error: FailedToRunTestError: Couldn't find the requested package
    at runTest (/Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:356:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) +0ms
Error:
Testing project-image-registry:test...

Couldn't find the requested package
    at test (/Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/snyk/src/cli/commands/test/index.ts:317:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

  snyk Exit code: 2 +0ms
  snyk analytics {
  args: [
    'project-image-registry:test',
    {
      debug: true,
      org: 'non-perm-org',
      'project-name': 'project-name:docker',
      file: 'Dockerfile',
      'json-file-output': 'reports/snyk-docker.json',
      docker: true,
      callGraphBuilderTimeout: '300',
      showVulnPaths: 'some'
    }
  ],
  command: 'bad-command',
  org: 'non-perm-org',
  metadata: {
    local: true,
    policies: 0,
    policyLocations: [],
    payloadSize: 9308,
    gzippedPayloadSize: 1982,
    'error-message': '\n' +
      'Testing project-image-registry:test...\n' +
      '\n' +
      "Couldn't find the requested package",
    error: 'Error: \n' +
      'Testing project-image-registry:test...\n' +
      '\n' +
      "Couldn't find the requested package\n" +
      '    at test (/Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/snyk/src/cli/commands/test/index.ts:317:19)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
    'error-code': 404,
    command: 'test'
  },
  version: '1.448.0',
  os: 'macOS Catalina',
  nodeVersion: 'v12.20.1',
  standalone: false,
  integrationName: '',
  integrationVersion: '',
  integrationEnvironment: '',
  integrationEnvironmentVersion: '',
  id: '0cb4c6efede9fbc6cb7756d16fc6916ff3db148c',
  ci: false,
  environment: { npmVersion: '6.14.10' },
  durationMs: 5927,
  metrics: {
    network_time: { type: 'timer', values: [Array], total: 333 },
    cpu_time: { type: 'synthetic', values: [Array], total: 5594 }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +516ms
  snyk request body size: 1374 +0ms
  snyk gzipped request body size: 730 +0ms
  snyk not using proxy +0ms
```

</details>

Inspecting the raw HTTP response from the call to `api/v1/test-dependencies` I can see that a meaningful message is returned that helped me understand what went wrong, but it is not inspected by [`run-test.ts`](https://github.com/snyk/snyk/blob/c7374f53bca6e11f3a10279fd329d61c71ce8ac8/src/lib/snyk-test/run-test.ts#L491-L493)

```
{
  code: 404,
  message: 'Org non-perm was not found or you may not have the correct permissions to access the org.\n' +
    'You can use the following orgs: another-org (org-guid).',
  error: 'Org non-perm was not found or you may not have the correct permissions to access the org.\n' +
    'You can use the following orgs: another-org (org-guid).',
  cliMessage: 'Org non-perm was not found or you may not have the correct permissions to access the org. Try re-running with the `--org` flag.\n' +
    'You can use the following orgs: another-org.',
  userMessage: 'Org non-perm was not found or you may not have the correct permissions to access the org. Try re-running with the `--org` flag.\n' +
    'You can use the following orgs: another-org.'
}
```

**Comment by artemptushkin** [comment]
Same for me.

I've made a guess that I'm not authed to my organization and the command below helped me.

`snyk auth $TOKEN_FROM_SETTINGS_AT_THE_PORTAL`

**Comment by mjftw** [comment]
Experienced a very similar same issue recently on a Scala (SBT) project.
Only difference was that there was no hint about a permissions issue.

Here's the relevant (redacted) output from running `snyk test -d --severity-threshold=high --fail-on=all`:

```
Couldn't find the requested package
--
929 | at test (/snapshot/snyk/dist/cli/commands/test/index.js:217:23)
930 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
931 | 2021-05-18T12:34:43.142Z snyk analytics {
932 | args: [
933 | {
934 | debug: true,
935 | severityThreshold: 'high',
936 | failOn: 'all',
937 | callGraphBuilderTimeout: '300',
938 | org: undefined,
939 | showVulnPaths: 'some'
940 | }
941 | ],
942 | command: 'bad-command',
943 | org: undefined,
944 | metadata: {
945 | local: true,
946 | pluginName: 'snyk:sbt',
947 | policies: 1,
948 | policyLocations: [
949 | '<REDACTED>'
950 | ],
951 | packageManager: 'sbt',
952 | packageName: '<REDACTED>',
953 | packageVersion: <REDACTED>',
954 | package: '<REDACTED>',
955 | prePrunedPathsCount: 729,
956 | payloadSize: 29353,
957 | gzippedPayloadSize: 3499,
958 | 'error-message': '\n' +
959 | 'Testing <REDACTED>' +
960 | '\n' +
961 | "Couldn't find the requested package",
962 | error: 'Error: \n' +
963 | 'Testing <REDACTED>' +
964 | '\n' +
965 | "Couldn't find the requested package\n" +
966 | '    at test (/snapshot/snyk/dist/cli/commands/test/index.js:217:23)\n' +
967 | '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
968 | 'error-code': 404,
969 | command: 'test'
970 | },
971 | version: '1.436.0',
972 | os: 'Linux 4.14',
973 | nodeVersion: 'v12.18.1',
974 | standalone: true,
975 | integrationName: '',
976 | integrationVersion: '',
977 | integrationEnvironment: '',
978 | integrationEnvironmentVersion: '',
979 | id: '<REDACTED>',
980 | ci: false,
981 | environment: {},
982 | durationMs: 17642,
983 | metrics: {
984 | network_time: { type: 'timer', values: [Array], total: 208 },
985 | cpu_time: { type: 'synthetic', values: [Array], total: 17434 }
986 | }
987 | }
988 | &nbsp;
989 | 2021-05-18T12:34:43.142Z snyk Exit code: 2
```

The solution for us was to generate a new API key in the "Service Accounts" section of the Snyk web UI and use that in the CI.
No idea why there was suddenly an issue with the old API key as it had been working for a very long time without issue.

**It would be much better if the error message "Couldn't find the requested package" was more helpful, as currently it's pretty misleading!**
