### ISSUE TITLE
[🐛] snyk iac test on directory crashes.

### ISSUE THREAD

**Issue by TheDukeDK** [snyk/snyk#1637]
- `snyk -v`:1.454.0
- OS: Linux (Debian 9)
- Command run: `snyk iac test k8s/`

### Expected behaviour
Snyk completes without error code.

### Actual behaviour
Snyk exits with error code.

`Internal error (reference: 5da97465-4fbd-448b-97b8-9cb6be670c90)`

### Steps to reproduce

- Clone this repo. https://github.com/TheDukeDK/devsecops-demo
- Change directory into sample_projects/eShopOnContainers
- Execute: `snyk iac test k8s/`

### Debug log
```
2021-02-15T11:12:14.193Z snyk test { _: [ 'k8s/', [Circular] ], debug: true, iac: true }
2021-02-15T11:12:14.832Z snyk:run-test Error running test { error:
   { FailedToGetVulnerabilitiesError: Failed to get vulns
       at handleTestHttpErrorResponse (/usr/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:506:13)
       at request (/usr/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:473:21)
       at module.exports (/usr/lib/node_modules/snyk/src/lib/request/index.ts:20:7)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'FailedToGetVulnerabilitiesError',
     code: 400,
     innerError:
      'Internal error (reference: 50fef702-0aa7-4bf0-b812-8de3a2fbe80f)',
     userMessage:
      'Internal error (reference: 50fef702-0aa7-4bf0-b812-8de3a2fbe80f)',
     strCode: 'INTERNAL_SERVER_ERROR' } }
2021-02-15T11:12:14.909Z snyk-test Failed to test 1 projects, errors:
2021-02-15T11:12:14.909Z snyk-test error: FailedToRunTestError: Internal error (reference: 50fef702-0aa7-4bf0-b812-8de3a2fbe80f)
    at runTest (/usr/lib/node_modules/snyk/src/lib/snyk-test/run-test.ts:359:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: 
Testing k8s/...

Internal error (reference: 50fef702-0aa7-4bf0-b812-8de3a2fbe80f)
    at test (/usr/lib/node_modules/snyk/src/cli/commands/test/index.ts:316:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Trimmed some repetitive output here. 
Debug info continued below.
```
2021-02-15T11:12:15.417Z snyk analytics { args:
   [ 'k8s/',
     { debug: true, iac: true, org: undefined, showVulnPaths: 'some' } ],
  command: 'bad-command',
  org: undefined,
  metadata:
   { local: true,
     'iac type':
      [ true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true ],
     payloadSize:
      [ 743,
        1475,
        25501,
        334,
        640,
        801,
        800,
        798,
        797,
        799,
        809,
        804,
        809,
        591,
        1314,
        819,
        814,
        814,
        838,
        802,
        809,
        872,
        847,
        804,
        793,
        792,
        809,
        812,
        780,
        823,
        780,
        795,
        626,
        1805,
        1241,
        759,
        776,
        537,
        1211,
        5886,
        5874,
        786,
        489,
        474,
        782,
        3946,
        1114,
        780,
        3188,
        937 ],
     gzippedPayloadSize:
      [ 362,
        586,
        1758,
        236,
        387,
        396,
        393,
        392,
        393,
        387,
        392,
        388,
        389,
        368,
        419,
        394,
        389,
        389,
        394,
        386,
        388,
        402,
        397,
        388,
        390,
        378,
        389,
        392,
        385,
        391,
        385,
        387,
        340,
        504,
        501,
        364,
        372,
        323,
        444,
        1274,
        1270,
        361,
        306,
        297,
        370,
        635,
        333,
        375,
        500,
        460 ],
     'error-message':
      '\nTesting k8s/...\n\nInternal error (reference: 50fef702-0aa7-4bf0-b812-8de3a2fbe80f)',
     error:
      'Error: \nTesting k8s/...\n\nInternal error (reference: 50fef702-0aa7-4bf0-b812-8de3a2fbe80f)\n    at test (/usr/lib/node_modules/snyk/src/cli/commands/test/index.ts:316:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     'error-code': 400,
     command: 'test' },
  version: '1.454.0',
  os: 'Linux 5.10',
  nodeVersion: 'v10.23.3',
  standalone: false,
  integrationName: '',
  integrationVersion: '',
  integrationEnvironment: '',
  integrationEnvironmentVersion: '',
  id: '812e60b3c72bae5576b0152146cddd4e87826f67',
  ci: false,
  environment: { npmVersion: '6.14.11' },
  durationMs: 1259,
  metrics:
   { network_time: { type: 'timer', values: [Array], total: 15297 },
     cpu_time: { type: 'synthetic', values: [Array], total: -14038 } } }
```

**Comment by TheDukeDK** [comment]
Running snyk on a single file succeeds. `snyk iac test k8s/deployments.yaml`.

**Comment by aron** [comment]
Hey @TheDukeDK, sorry for the slow response time for this. I've just had a look at your project. Currently the CLI doesn't support scanning Helm files. Instead we recommend that you generate the Kubernetes configuration from the Helm templates and pass those through to the CLI.

```
helm template ./k8s/helm > helm.yaml
snyk iac test helm.yaml
```

- [Kubernetes CLI Documentation](https://support.snyk.io/hc/en-us/articles/360012429477-Test-your-Kubernetes-files-with-our-CLI-tool)

Testing the non-helm files in your project folder everything seems to be running as expected and generating output. It's on our radar to improve the error messaging here and try and pick this up without erroring.

If you have any follow up questions please reach out.

**Comment by TheDukeDK** [comment]
Excellent. Thanks for the feedback.

**Comment by ipapast** [comment]
Closing this as issue was solved, please reach out if you need anything else.
