### ISSUE TITLE
[🐛] snyk auth  ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by darthvader666uk** [snyk/snyk#1710]
- `node -v`:v11.15.0
- `npm -v`:7.6.2
- `snyk -v`: produces error as below
- OS: (e.g. OSX, Linux, Windows, ...): Windows via Git Bash
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)snyk auth

### Expected behaviour
I was tryting to use snyk.  I used `npm install -g snyk` and completed then ran `snyk auth` and it produced the below error.

### Actual behaviour
snyk auth

C:\laragon\bin\nodejs\node\node_modules\snyk\node_modules\queue-microtask\index.js:5
  ? queueMicrotask.bind(globalThis)
                        ^
ReferenceError: globalThis is not defined
    at Object.<anonymous> (C:\laragon\bin\nodejs\node\node_modules\snyk\node_modules\queue-microtask\index.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\laragon\bin\nodejs\node\node_modules\snyk\node_modules\run-parallel\index.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)

### Steps to reproduce
 `npm install -g snyk`

Then 

`snyk auth`

**Comment by JackuB** [comment]
Hey, thanks for reporting this. From what I've tested, it seems like it's affecting only Node v11, which is unsupported as of April 22nd 2019. I highly recommend upgrading if possible. Or alternatively, if you need this Node version, there are executable builds available https://github.com/snyk/snyk/releases/tag/v1.483.0

We do test CLI only with the latest odd-numbered Node.js release https://github.com/snyk/snyk/blob/0b0d28c78c949d0a06b513873980ce9d0f0f3b9b/.github/workflows/smoke-tests.yml#L20

**Comment by darthvader666uk** [comment]
> 
> 
> Hey, thanks for reporting this. From what I've tested, it seems like it's affecting only Node v11, which is unsupported as of April 22nd 2019. I highly recommend upgrading if possible. Or alternatively, if you need this Node version, there are executable builds available https://github.com/snyk/snyk/releases/tag/v1.483.0
> 
> We do test CLI only with the latest odd-numbered Node.js release
> 
> https://github.com/snyk/snyk/blob/0b0d28c78c949d0a06b513873980ce9d0f0f3b9b/.github/workflows/smoke-tests.yml#L20

thank you so much for that!

yep for that project it was restricted to node 11 BUT those executable builds are perfecxt thank you :)
