### ISSUE TITLE
Wizard crashes on startup with "TypeError: prompts.forEach is not a function"

### ISSUE THREAD

**Issue by jeffclemens** [snyk/snyk#175]
- `node -v`: v8.11.2
- `npm -v`: 6.1.0
- `yarn -v`: 1.7.0
- `snyk -v`: 1.88.1
- Command run:

`snyk wizard`

### Expected behaviour

The wizard runs.

### Actual behaviour

The wizard crashes: 
```
  snyk wizard { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder /Users/xxxxxxx/dev/snyk-bug +0ms
  snyk found package file yarn.lock in /Users/xxxxxxx/dev/snyx-bug +0ms
/usr/local/lib/node_modules/snyk/cli/commands/protect/wizard.js:220
  prompts.forEach(function (prompt) {
          ^

TypeError: prompts.forEach is not a function
    at inquire (/usr/local/lib/node_modules/snyk/cli/commands/protect/wizard.js:220:11)
    at processPackageManager (/usr/local/lib/node_modules/snyk/cli/commands/protect/wizard.js:76:12)
    at wizard (/usr/local/lib/node_modules/snyk/cli/commands/protect/wizard.js:53:10)
    at /usr/local/lib/node_modules/snyk/lib/hotload.js:16:21
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/cli/index.js:27:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

### Steps to reproduce

1.   Create an app.  For example: 
```
npx create-react-app my-app
cd my-app
```

2. Run `snyk wizard`.

**Comment by joshje** [comment]
Hi @jeffclemens, we discovered a regression with support for `snyk wizard` with `yarn` projects. 

Please install the latest release [1.88.2](https://github.com/snyk/snyk/releases/tag/v1.88.2) and try again.

Have a great weekend!
