### ISSUE TITLE
Can't run snyk on .NET project

### ISSUE THREAD

**Issue by bruno-garcia** [snyk/snyk#178]
- `node -v`: v8.9.4
- `npm -v`: 5.6.0
- `snyk -v`: 1.89.0

I'm trying to run `snyk` on a .NET project without success. The [project is hosted on GitHub](https://github.com/getsentry/dotnet-sentry-platform-abstractions) but I'm running `snyk` locally **after building the solution**.

The projects *obj\project.assets.json* are available but still, it won't work.
At the root of the repo, I run:

```sh
$ snyk test
Could not autodetect package manager for C:\Users\bruno\git\sentry-dotnet-platform-abstractions
```

And with:
```sh
$ snyk test --packageManager=nuget
Could not determine manifest type for sentry-dotnet-platform-abstractions
```

If I enter the project directory src\Sentry.PlatformAbstraction which was built and includes *obj\project.asserts.json* and try:

```sh
$ snyk test
Cannot convert undefined or null to object
```

#143 would solve this problem since the analysis of dependencies would happen without the need to build the solution.

The first two commands fail to locate the manifest/package manager detection so less relevant.
I'd really expect the last attempt to work. 
Here's debug log of the last `snyk test`, at the project folder:

```sh
λ snyk test --debug
  snyk test { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder C:\Users\bruno\git\sentry-dotnet-platform-abstractions\src\Sentry.PlatformAbstractions +0ms
  snyk found package file obj/project.assets.json in C:\Users\bruno\git\sentry-dotnet-platform-abstractions\src\Sentry.PlatformAbstractions +2ms
  snyk analytics add local true +0ms
  snyk found package file obj/project.assets.json in C:\Users\bruno\git\sentry-dotnet-platform-abstractions\src\Sentry.PlatformAbstractions +4ms
  snyk Looking for your .csproj file in C:\Users\bruno\git\sentry-dotnet-platform-abstractions\src\Sentry.PlatformAbstractions +0ms
  snyk Checking .net framework version in .csproj file C:\Users\bruno\git\sentry-dotnet-platform-abstractions\src\Sentry.PlatformAbstractions\Sentry.PlatformAbstractions.csproj +1ms
  snyk Loaded obj/project.assets.json with manifest type dotnet-core for .NET version [object Object],[object Object],[object Object],[object Object],[object Object],[object Object] +0ms
  snyk Trying to parse dot-net-cli manifest +3ms
  snyk Available frameworks: 'net35,net40,net45,net471,netstandard1.5,netstandard2.0' +0ms
  snyk Selected framework: 'net35' +2ms
  snyk Available targets: '.NETFramework,Version=v3.5,.NETFramework,Version=v4.0,.NETFramework,Version=v4.5,.NETFramework,Version=v4.7.1,.NETStandard,Version=v1.5,.NETStandard,Version=v2.0' +1ms
  snyk Selected target: '.NETFramework,Version=v3.5' +0ms
  snyk analytics add error-message
Testing C:\Users\bruno\git\sentry-dotnet-platform-abstractions\src\Sentry.PlatformAbstractions...

Cannot convert undefined or null to object +99ms
  snyk analytics add error Error:
Testing C:\Users\bruno\git\sentry-dotnet-platform-abstractions\src\Sentry.PlatformAbstractions...

Cannot convert undefined or null to object
    at C:\Users\bruno\AppData\Roaming\npm\node_modules\snyk\cli\commands\test.js:142:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3 +2ms
  snyk analytics add error-code undefined +3ms
  snyk analytics add command test +0ms
Error:
Testing C:\Users\bruno\git\sentry-dotnet-platform-abstractions\src\Sentry.PlatformAbstractions...

Cannot convert undefined or null to object
    at C:\Users\bruno\AppData\Roaming\npm\node_modules\snyk\cli\commands\test.js:142:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  snyk analytics { command: 'bad-command',
  args: [ { debug: true, org: undefined, showVulnPaths: true } ],
  metadata:
   { local: true,
     'error-message': '\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting C:\\Users\\bruno\\git\\sentry-dotnet-platform-abstractions\\src\\Sentry.PlatformAbstractions...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mCannot convert undefined or null to object',
     error: 'Error: \u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting C:\\Users\\bruno\\git\\sentry-dotnet-platform-abstractions\\src\\Sentry.PlatformAbstractions...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mCannot convert undefined or null to object\n    at C:\\Users\\bruno\\AppData\\Roaming\\npm\\node_modules\\snyk\\cli\\commands\\test.js:142:21\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)\n    at Function.Module.runMain (module.js:686:11)\n    at startup (bootstrap_node.js:187:16)\n    at bootstrap_node.js:608:3',
     'error-code': undefined,
     command: 'test' },
  version: '1.89.0',
  os: 'Windows 10',
  nodeVersion: 'v8.9.4',
  id: '7b1c631aab8a97fd401f19e23f7d477e9be69e3e',
  ci: false,
  durationMs: 136 } +7ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1222 +1ms
  snyk gzipped request body size: 520 +0ms
  snyk not using proxy +1ms
```

**Comment by tomkerkhove** [comment]
This seems to be working now for me when using v1.92.6

**Comment by adrukh** [comment]
Thanks @tomkerkhove !

Can you please provide the debug output (`snyk test -d`) so we can see how we work around the issue now?

Asking because we haven't deliberately addressed this issue yet, so we're probably still missing something.

**Comment by tomkerkhove** [comment]
Sure - I've uploaded it to this [gist](https://gist.github.com/tomkerkhove/18badf934f223a162d8ad86508d11750).

It first logged tons of entries as mentioned in the beginning of the gist and exited with the rest of the log.

**Comment by lili2311** [comment]
@tomkerkhove we have released many updates, since the last comment here. Please confirm if this is still an issue?
