### ISSUE TITLE
Can't run snyk for Golang on Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by roman-vynar** [snyk/snyk#179]
- `node -v`: v8.11.3, v10.3.0, v10.7.0 - neither works
- `npm -v`: corresponding version from the above package ^^
- `snyk -v`: 1.89.0
- Ubuntu 16.04.4 LTS running in Docker
- Command run: `./node_modules/.bin/snyk test --file=Gopkg.lock`

### Expected behaviour

```
Testing /home/jenkins...

Organisation:    roman.vynar
Package manager: golangdep
Target file:     Gopkg.lock
Open source:     no
Project path:    /home/jenkins

✓ Tested 99 dependencies for known vulnerabilities, no vulnerable paths found.
```
Works from MacOS.

### Actual behaviour
```
Testing /home/jenkins...

Cannot read property 'removeCallback' of undefined

```
Does not work on Ubuntu and any version of node.

### Debug
```
root@93018e9e6698:/home/jenkins# ./node_modules/.bin/snyk test --file=Gopkg.lock --debug
  snyk test æ _: Æ ÆCircularÅ Å, file: 'Gopkg.lock', debug: true å +0ms
  snyk analytics add local true +0ms
  snyk analytics add error-message 
Testing /home/jenkins...

Cannot read property 'removeCallback' of undefined +328ms
  snyk analytics add error Error: 
Testing /home/jenkins...

Cannot read property 'removeCallback' of undefined
    at /home/jenkins/node_modules/snyk/cli/commands/test.js:142:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3 +1ms
  snyk analytics add error-code undefined +0ms
  snyk analytics add command test +0ms
Error: 
Testing /home/jenkins...

Cannot read property 'removeCallback' of undefined
    at /home/jenkins/node_modules/snyk/cli/commands/test.js:142:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
  snyk analytics æ command: 'bad-command',
  args: 
   Æ æ file: 'Gopkg.lock',
       debug: true,
       org: undefined,
       showVulnPaths: true å Å,
  metadata: 
   æ local: true,
     'error-message': 'Øu001bÆ1mØu001bÆ37mØu001bÆ39mØu001bÆ22mØnØu001bÆ1mØu001bÆ37mTesting /home/jenkins...Øu001bÆ39mØu001bÆ22mØnØu001bÆ1mØu001bÆ37mØu001bÆ39Øu001bÆ22mØnØu001bÆ1mØu001bÆ37mØu001bÆ39mØu001bÆ22mCannot read property Ø'removeCallbackØ' of undefined',
     error: 'Error: Øu001bÆ1mØu001bÆ37mØu001bÆ39mØu001bÆ22mØnØu001bÆ1mØu001bÆ37mTesting /home/jenkins...Øu001bÆ39mØu001bÆ22mØnØu001bÆ1mØu001bÆ37mØu001bÆ39mØu001bÆ22mØnØu001bÆ1mØu001bÆ37mØu001bÆ39mØu001bÆ22mCannot read property Ø'removeCallbackØ' of undefinedØn    at /home/jenkins/node_modules/snyk/cli/commands/test.js:142:21Øn    at <anonymous>Øn    at process._tickCallback (internal/process/next_tick.js:188:7)Øn    at Function.Module.runMain (module.js:695:11)Øn    at startup (bootstrap_node.js:191:16)Øn    at bootstrap_node.js:612:3',
     'error-code': undefined,
     command: 'test' å,
  version: '1.89.0',
  os: 'Linux 4.4',
  nodeVersion: 'v8.11.3',
  id: '0ec7e97e155f8f2e1a9a6fc2f6e8b5c016ae9803',
  ci: false,
  durationMs: 342 å +2ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1069 +0ms
  snyk gzipped request body size: 474 +0ms
  snyk not using proxy +1ms
```

Any suggestion?

**Comment by michael-go** [comment]
Hi @roman-vynar. Thanks for reporting this.
From the error stack it's not clear if the error is related to Golang. Can you please help narrow it down by:
1. Testing a Node.js project inside this Docker? (seems you are already inside one, so just `./node_modules/.bin/snyk test --debug`
2. Making sure you have Golang installed inside the Docker, and the `go` command available.

Thanks!

**Comment by roman-vynar** [comment]
Hi Michael,

Thanks for the reply!

Yes, I didn't `go` inside the container. Now I have installed it.
I don't place the source code of my project into the container, I am trying to have snyk to test a standalone `Gopkg.lock`.

So what I do:
- create a docker container
- install go and snyk:
```
root@f249de9b8fd2:~# cat /etc/lsb-release |grep LTS
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
root@f249de9b8fd2:~# go version
go version go1.10.3 linux/amd64
root@f249de9b8fd2:~# ./node_modules/.bin/snyk -v          
1.89.1
```
- copy `Gopkg.lock` from my project (just pasting content)
- run:
```
 ./node_modules/.bin/snyk test --file=Gopkg.lock
```
And getting the output like above.

Just straight test with debug on the root dir shows:
```
root@f249de9b8fd2:~# ./node_modules/.bin/snyk test --debug          
  snyk test { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder /root +0ms
  snyk found package file Gopkg.lock in /root +0ms
  snyk analytics add local true +0ms
  snyk found package file Gopkg.lock in /root +2ms
  snyk analytics add error-message 
Testing /root...

Cannot read property 'removeCallback' of undefined +151ms
  snyk analytics add error Error: 
Testing /root...

Cannot read property 'removeCallback' of undefined
    at /root/node_modules/snyk/cli/commands/test.js:142:21
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3) +0ms
  snyk analytics add error-code undefined +0ms
  snyk analytics add command test +0ms
Error: 
Testing /root...

Cannot read property 'removeCallback' of undefined
    at /root/node_modules/snyk/cli/commands/test.js:142:21
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
  snyk analytics { command: 'bad-command',
  args: [ { debug: true, org: undefined, showVulnPaths: true } ],
  metadata:
   { local: true,
     'error-message':
      '\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting /root...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mCannot read property \'removeCallback\' of undefined',
     error:
      'Error: \u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting /root...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mCannot read property \'removeCallback\' of undefined\n    at /root/node_modules/snyk/cli/commands/test.js:142:21\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)\n    at startup (internal/bootstrap/node.js:238:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)',
     'error-code': undefined,
     command: 'test' },
  version: '1.89.1',
  os: 'Linux 4.4',
  nodeVersion: 'v10.3.0',
  id: '88d02e90ce036339f783789110448b7b04d83307',
  ci: false,
  durationMs: 165 } +2ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1065 +0ms
  snyk gzipped request body size: 464 +0ms
  snyk not using proxy +1ms
```

So I don't have a Node.JS project to test as my project is Golang-based and I was thinking it may work if I just pass Gopkg.lock?

**Comment by michael-go** [comment]
Hi @roman-vynar. 

Sorry, it's not currently possible to use `snyk test` on Go just with the `Gopkg.lock`, as `snyk` tries to build the full dependency tree, and for that it has to scan the actual `import` statements in source tree and the `vendor/` folder.

**Comment by roman-vynar** [comment]
@michael-go Thanks. 

It's clear now, so the code and vendor/ is required. It works now!
