### ISSUE TITLE
[🐛] snyk iac providing error "Cannot read property 'hasOwnProperty' of null" while parsing K8 yaml file

### ISSUE THREAD

**Issue by Gururajnrao** [snyk/snyk#1919]
- `node -v`: v16.1.0
- `npm -v`: 7.11.2
- `snyk -v`: 1.595.0
- OS: (e.g. OSX, Linux, Windows, ...) : Linux
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)
snyk iac test -d iac.yaml

snippet of iac.yaml (generated with helm template)
==
---
# Source: example/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-chart
  labels:
    app.kubernetes.io/name: nginx-app
    helm.sh/chart: example-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: release-name

---
# Source: example/templates/deployment.yaml
apiVersion: v1
kind: Deployment
metadata:
  name: nginx-chart
  labels:
    app.kubernetes.io/name: nginx-app
    helm.sh/chart: example-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-app
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-app
        app.kubernetes.io/instance: release-name
    spec:
     # securityContext: 
     #    runAsNonRoot: true
      containers:
        - name: example
          image: "nginx:stable"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
            

---
# Source: example/templates/ingress.yaml

====

### Expected behaviour
Parse the iac.yaml and report errors
### Actual behaviour
snyk iac test -d iac.yaml

2021-05-15T14:12:12.391Z snyk test <ref *1> { _: [ 'iac.yaml', [Circular *1] ], debug: true, iac: true }

2021-05-15T14:12:13.634Z snyk test <ref *1> { _: [ 'iac.yaml', [Circular *1] ], debug: true, iac: true }

2021-05-15T14:12:13.637Z snyk not using proxy

2021-05-15T14:12:13.832Z snyk not using proxy

2021-05-15T14:12:16.423Z snyk-test Failed to test 1 projects, errors:

2021-05-15T14:12:16.458Z snyk-test error: TypeError: Cannot read property 'hasOwnProperty' of null

    at /usr/local/lib/node_modules/snyk/src/cli/commands/test/iac-local-execution/parsers/kubernetes-parser.ts:33:28

    at Array.every (<anonymous>)

    at /usr/local/lib/node_modules/snyk/src/cli/commands/test/iac-local-execution/parsers/kubernetes-parser.ts:32:27

    at Array.map (<anonymous>)

    at Object.tryParsingKubernetesFile (/usr/local/lib/node_modules/snyk/src/cli/commands/test/iac-local-execution/parsers/kubernetes-parser.ts:30:24)

    at tryParseIacFile (/usr/local/lib/node_modules/snyk/src/cli/commands/test/iac-local-execution/file-parser.ts:91:14)

    at parseFiles (/usr/local/lib/node_modules/snyk/src/cli/commands/test/iac-local-execution/file-parser.ts:34:27)

    at Object.parseFiles (/usr/local/lib/node_modules/snyk/src/cli/commands/test/iac-local-execution/measurable-methods.ts:34:31)

    at test (/usr/local/lib/node_modules/snyk/src/cli/commands/test/iac-local-execution/index.ts:29:46)

    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/src/cli/commands/test/iac-local-execution/measurable-methods.ts:34:25)

    at test (/usr/local/lib/node_modules/snyk/src/cli/commands/test/index.ts:105:39)

    at runCommand (/usr/local/lib/node_modules/snyk/src/cli/index.ts:56:25)

    at main (/usr/local/lib/node_modules/snyk/src/cli/index.ts:309:11)

Error: 

Testing iac.yaml...

Cannot read property 'hasOwnProperty' of null

    at test (/usr/local/lib/node_modules/snyk/src/cli/commands/test/index.ts:257:19)

    at runCommand (/usr/local/lib/node_modules/snyk/src/cli/index.ts:56:25)

    at main (/usr/local/lib/node_modules/snyk/src/cli/index.ts:309:11)

2021-05-15T14:12:16.470Z snyk Exit code: 2

2021-05-15T14:12:16.706Z snyk analytics {

  "args": [

    "iac.yaml",

    {

      "debug": true,

      "iac": true

    }

  ],

  "command": "bad-command",

  "metadata": {

    "iac-terraform-plan": false,

    "error-message": "\nTesting iac.yaml...\n\nCannot read property 'hasOwnProperty' of null",

    "error": "Error: \nTesting iac.yaml...\n\nCannot read property 'hasOwnProperty' of null\n    at test (/usr/local/lib/node_modules/snyk/src/cli/commands/test/index.ts:257:19)\n    at runCommand (/usr/local/lib/node_modules/snyk/src/cli/index.ts:56:25)\n    at main (/usr/local/lib/node_modules/snyk/src/cli/index.ts:309:11)",

    "command": "test"

  },

  "version": "1.595.0",

  "os": "Linux 4.9",

  "nodeVersion": "v16.1.0",

  "standalone": false,

  "integrationName": "",

  "integrationVersion": "",

  "integrationEnvironment": "",

  "integrationEnvironmentVersion": "",

  "id": "d6355e27ca960626f7e86056c80b56aeb3708a81",

  "ci": true,

  "environment": {

    "npmVersion": "7.11.2"

  },

  "durationMs": 3546,

  "metrics": {

    "network_time": {

      "type": "timer",

      "values": [

        194,

        2234

      ],

      "total": 2428

    },

    "cpu_time": {

      "type": "synthetic",

      "values": [

        1118

      ],

      "total": 1118

    }

  }

}

2021-05-15T14:12:16.707Z snyk sending request to: https://snyk.io/api/v1/analytics/cli

2021-05-15T14:12:16.707Z snyk request body size: 989

2021-05-15T14:12:16.707Z snyk gzipped request body size: 495

2021-05-15T14:12:16.708Z snyk not using proxy

script returned exit code 2

### Debug log
If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by ipapast** [comment]
hey @Gururajnrao , apologies for the very late reply. This looks like an old bug in our CLI which has now been resolved. I tried scanning the files with the latest version and the scanning succeeds. Could you try upgrading the `snyk` package and scanning the files again?
Thank you
