### ISSUE TITLE
[🐛] Internal error when running `snyk monitor --dev`

### ISSUE THREAD

**Issue by buck06191** [snyk/snyk#2011]
- `node -v`: v14.15.4
- `npm -v`: 6.14.10
- `snyk -v`: 1.623.0
- OS: OSX Mojave/Ubuntu (Github Action)
- Command run: `snyk monitor  --dev=true`

### Expected behaviour

`snyk monitor` runs without aan error

### Actual behaviour

```
Internal error (reference: c4e46d2a-6533-4949-9d0d-a5b7c9419cca)
    at monitor (/Users/josh_russell-bucklan/.config/yarn/global/node_modules/snyk/src/cli/commands/monitor/index.ts:282:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runCommand (/Users/josh_russell-bucklan/.config/yarn/global/node_modules/snyk/src/cli/index.ts:56:25)
    at main (/Users/josh_russell-bucklan/.config/yarn/global/node_modules/snyk/src/cli/index.ts:312:11)
```

### Steps to reproduce

When running `snyk monitor` against a Javascript project and checking `devDependencies`, I get the above internal error. If I remove the `--dev=true` flag then it works fine. This fails both locally and when run using a Github action. `snyk test` does work when running against `devDependencies`.

### Debug log
```
snyk monitor <ref *1> {
  _: [ [Circular *1] ],
  org: 'the-guardian',
  dev: 'true',
  debug: true
} +0ms
  snyk Processing /Users/josh_russell-bucklan/code/discussion-rendering... +0ms
  snyk getDepsFromPlugin ... +1ms
  snyk-test Analyzing npm dependencies for /Users/josh_russell-bucklan/code/discussion-rendering/yarn.lock +0ms
  snyk Processing @guardian/discussion-rendering... +645ms
  snyk not using proxy +0ms
  snyk Potential policy locations found: [ '/Users/josh_russell-bucklan/code/discussion-rendering' ] +0ms
  snyk sending request to: https://snyk.io/api/v1/monitor/yarn/graph +1s
  snyk request body size: 770201 +0ms
  snyk gzipped request body size: 96575 +0ms
  snyk not using proxy +1ms
Error:
Monitoring /Users/josh_russell-bucklan/code/discussion-rendering...

Internal error (reference: c4e46d2a-6533-4949-9d0d-a5b7c9419cca)
    at monitor (/Users/josh_russell-bucklan/.config/yarn/global/node_modules/snyk/src/cli/commands/monitor/index.ts:282:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runCommand (/Users/josh_russell-bucklan/.config/yarn/global/node_modules/snyk/src/cli/index.ts:56:25)
    at main (/Users/josh_russell-bucklan/.config/yarn/global/node_modules/snyk/src/cli/index.ts:312:11)

  snyk Exit code: 2 +0ms
  snyk analytics {
  "args": [
    {
      "org": "[redacted]",
      "dev": "true",
      "debug": true
    }
  ],
  "command": "bad-command",
  "org": "[redacted]",
  "metadata": {
    "local": true,
    "generating-node-dependency-tree": {
      "lockFile": true,
      "targetFile": "yarn.lock"
    },
    "lockfileVersion": 1,
    "pluginName": "snyk-nodejs-lockfile-parser",
    "packageManager": [
      "yarn",
      "yarn"
    ],
    "isDocker": false,
    "experimentalMonitorDepGraphFromDepTree": true,
    "policies": 1,
    "policyLocations": [
      "/Users/josh_russell-bucklan/code/discussion-rendering"
    ],
    "targetBranch": "josh/add-snyk-gh-actions",
    "payloadSize": 770201,
    "gzippedPayloadSize": 96575,
    "error-message": "\nMonitoring /Users/josh_russell-bucklan/code/discussion-rendering...\n\nInternal error (reference: c4e46d2a-6533-4949-9d0d-a5b7c9419cca)",
    "error": "Error: \nMonitoring /Users/josh_russell-bucklan/code/discussion-rendering...\n\nInternal error (reference: c4e46d2a-6533-4949-9d0d-a5b7c9419cca)\n    at monitor (/Users/josh_russell-bucklan/.config/yarn/global/node_modules/snyk/src/cli/commands/monitor/index.ts:282:9)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at runCommand (/Users/josh_russell-bucklan/.config/yarn/global/node_modules/snyk/src/cli/index.ts:56:25)\n    at main (/Users/josh_russell-bucklan/.config/yarn/global/node_modules/snyk/src/cli/index.ts:312:11)",
    "command": "monitor"
  },
  "version": "1.623.0",
  "os": "macOS Mojave",
  "nodeVersion": "v14.15.4",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "35586850d01ef7c537706a1f0d3072be5957c57b",
  "ci": false,
  "environment": {
    "npmVersion": "6.14.10"
  },
  "durationMs": 11577,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [
        331,
        3772
      ],
      "total": 4103
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        7474
      ],
      "total": 7474
    }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +9s
  snyk request body size: 1744 +0ms
  snyk gzipped request body size: 794 +0ms
  ```

**Comment by lili2311** [comment]
hi @buck06191 looking at the logs it seems there are too many vulnerable paths in this project and it is hitting our internal limits. Does the project succeed for you without `--dev`?

Could you try it also with `snyk monitor --prune-repeated-subdependencies` and see if this helps? This will drop any duplicate paths we have seen before but will not affect the issues found.

**Comment by buck06191** [comment]
> hi @buck06191 looking at the logs it seems there are too many vulnerable paths in this project and it is hitting our internal limits. Does the project succeed for you without `--dev`?
> 
> Could you try it also with `snyk monitor --prune-repeated-subdependencies` and see if this helps? This will drop any duplicate paths we have seen before but will not affect the issues found.

@lili2311 Hey thank for getting back. I'll give it a go today and get back to you!

**Comment by lili2311** [comment]
@buck06191 Just to let you know we are working on some improvements across our product that would allow us to handle larger number of vulnerable paths without the need of this pruning mechanism. The changes required are large, many and span across many areas of our product so the progress on this is slower.
I will close this issue as you have a working solution. Please do re-open if this is no longer working for you.
