### ISSUE TITLE
[🐛] UTF-16 BOM encoded .sln causes failure to detect .net projects

### ISSUE THREAD

**Issue by asos-chrishimsworth** [snyk/snyk#2094]
- `node -v`: 16.5.0
- `npm -v`: 7.19.0
- `snyk -v`: 1.661.0
- OS: Windows
- Command run: snyk test --file:solution.sln

### Expected behaviour

All the projects in the solution are scanned

### Actual behaviour

Could not detect supported target files in .
Please see our documentation for supported languages and target files: https://support.snyk.io/hc/en-us/articles/360000911957-Language-support and make sure you are in the right directory.

### Steps to reproduce

Create .sln file with UTF-16 BOM encoding and run the test command.
If the encoding of the file is changed to UTF-8 BOM, then the file is successfully parsed.

### Debug log

snyk test -d --file=solution.sln
  snyk test <ref *1> {
  _: [ [Circular *1] ],
  debug: true,
  file: 'solution.sln'
} +0ms
  snyk extracted paths from solution file:  [] +0ms
  snyk valid project folders in solution:  [] +1ms
CustomError: Could not detect supported target files in .
Please see our documentation for supported languages and target files: https://support.snyk.io/hc/en-us/articles/360000911957-Language-support and make sure you are in the right directory.
    at Object.NoSupportedManifestsFoundError (npm\node_modules\snyk\src\lib\errors\no-supported-manifests-found.ts:16:17)
    at Object.exports.updateArgs (npm\node_modules\snyk\src\lib\sln\index.ts:59:11)
    at main (npm\node_modules\snyk\src\cli\index.ts:285:11)
    at Object.<anonymous> (npm\node_modules\snyk\src\cli\index.ts:334:13)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

  snyk Exit code: 3 +0ms
  snyk analytics {
  "args": [
    {
      "debug": true,
      "file": "solution.sln"
    }
  ],
  "command": "bad-command",
  "metadata": {
    "error-message": "Could not detect supported target files in .\nPlease see our documentation for supported languages and target files: https://support.snyk.io/hc/en-us/articles/360000911957-Language-support and make sure you are in the right directory.",
    "error": "CustomError: Could not detect supported target files in .\nPlease see our documentation for supported languages and target files: https://support.snyk.io/hc/en-us/articles/360000911957-Language-support and make sure you are in the right directory.\n    at Object.NoSupportedManifestsFoundError (Roaming\\npm\\node_modules\\snyk\\src\\lib\\errors\\no-supported-manifests-found.ts:16:17)\n    at Object.exports.updateArgs (Roaming\\npm\\node_modules\\snyk\\src\\lib\\sln\\index.ts:59:11)\n    at main (Roaming\\npm\\node_modules\\snyk\\src\\cli\\index.ts:285:11)\n    at Object.<anonymous> (Roaming\\npm\\node_modules\\snyk\\src\\cli\\index.ts:334:13)\n    at Module._compile (node:internal/modules/cjs/loader:1095:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)\n    at Module.load (node:internal/modules/cjs/loader:975:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:816:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)\n    at node:internal/main/run_main_module:17:47",
    "error-code": 422,
    "command": "test"
  },
  "version": "1.661.0",
  "os": "Windows 10",
  "nodeVersion": "v16.5.0",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "7e6754c32364f617c187be26445f099811191cbb",
  "ci": false,
  "environment": {
    "npmVersion": "7.19.1"
  },
  "durationMs": 1526,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [],
      "total": 0
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        1526
      ],
      "total": 1526
    }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 2056 +0ms
  snyk gzipped request body size: 819 +1ms
  snyk not using proxy +1ms

**Comment by lili2311** [comment]
hi @asos-chrishimsworth! Would you have an example project for us to use to replicate the issue?
