### ISSUE TITLE
[🐛] 'pip' doesn't support graphs.

### ISSUE THREAD

**Issue by mishless** [snyk/snyk#2193]
- `node -v`: v16.7.0
- `npm -v`: 7.20.3
- `snyk -v`: 1.688.0
- OS: OSX
- Command run: `snyk monitor` in a Python project

### Expected behaviour

I expect this to create a new project in the web app.

### Actual behaviour

It fails with error: `'pip' doesn't support graphs.`

### Steps to reproduce

```
$ git clone https://github.com/johnthagen/python-blueprint.git
$ cd python-blueprint/
$ pip install -r requirements.txt
$ snyk monitor
```

### Debug log

```
$ snyk monitor --debug
  snyk monitor <ref *1> { _: [ [Circular *1] ], debug: true } +0ms
  snyk Processing /Users/m.stoycheva/Documents/Projects/python-blueprint... +0ms
  snyk getDepsFromPlugin ... +2ms
  snyk Processing python-blueprint... +429mss.txt
  snyk Potential policy locations found: [ '/Users/m.stoycheva/Documents/Projects/python-blueprint' ] +0ms
  snyk:prune rootPkg { name: 'python-blueprint', version: '0.0.0' } +0ms
  snyk:prune prePrunePathsCount: 5 +0ms
  snyk:prune isDenseGraph false +0ms
  snyk sending request to: https://snyk.io/api/v1/monitor/pip/graph +0ms
  snyk request body size: 1497 +0ms
  snyk gzipped request body size: 657 +0ms
  snyk not using proxy +1ms
Error: 
Monitoring /Users/m.stoycheva/Documents/Projects/python-blueprint...

'pip' doesn't support graphs.
    at monitor (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/monitor/index.ts:292:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runCommand (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:58:25)
    at main (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:316:4)
  snyk Exit code: 2 +0ms
```

Here I should mention that everything works just fine with snyk version 1.687.0 - the dependencies are analysed and the snapshot is created. The problems described above happened once I used the newest snyk version: 1.688.0

**Comment by liz-lawrens** [comment]
I am having this issue in the latest version 1.715.0

**Comment by zhiltsov-max** [comment]
1.696 looks like a working one.
