### ISSUE TITLE
[🐛] "Cannot read property 'length' of undefined" on .NET projects with TargetFrameworks read from Directory.Build.props

### ISSUE THREAD

**Issue by ugumba** [snyk/snyk#2217]
Trying to run "snyk test" on a ASP.NET Core solution with ~100 projects.  
It fails with the error message for ~20 projects, while the rest work well.
The debug output below is from running on one particular project.

It seems that snyk does not support MSBuild properties read from a shared Directory.Build.props, which is kind of crucial in managing large solutions.

If I add the TargetFrameworks property explicitly to the .csproj, snyk works.

- `node -v`: v14.17.6
- `npm -v`: 6.14.15
- `snyk -v`: 1.696.0
- OS: Windows
- Command run: `snyk test`

### Expected behaviour

Completion

### Actual behaviour

"Cannot read property 'length' of undefined"

### Steps to reproduce

Any .csproj with TargetFramework or TargetFrameworks read from a Directory.Build.props file inherited from a directory above.

### Debug log

```
  snyk test <ref *1> { _: [ [Circular *1] ], dev: true, debug: true } +0ms
  snyk Parsing content of C:\Git\nextGen\Avary2\Cegal.Platform.Flow\src\Cegal.Core.Immutable\obj\project.assets.json +0ms
  snyk Looking for your .csproj file in C:\Git\nextGen\Avary2\Cegal.Platform.Flow\src\Cegal.Core.Immutable +0ms
  snyk Checking .net framework version in .csproj file C:\Git\nextGen\Avary2\Cegal.Platform.Flow\src\Cegal.Core.Immutable\Cegal.Core.Immutable.csproj +1ms
  snyk:run-test Error running test {
  error: TypeError: Cannot read property 'length' of undefined
      at C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nuget-plugin\dist\nuget-parser\csproj-parser.js:38:1
      at Parser.<anonymous> (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\xml2js\lib\parser.js:305:10)
      at Parser.emit (events.js:400:28)
      at Parser.emit (domain.js:470:12)
      at SAXParser.onclosetag (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\xml2js\lib\parser.js:263:1)
      at emit (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\sax\lib\sax.js:625:1)
      at emitNode (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\sax\lib\sax.js:630:1)
      at closeTag (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:198235:7)
      at SAXParser.write (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\sax\lib\sax.js:1437:13)
      at Parser.__webpack_modules__.99082.exports.Parser.Parser.parseString (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\xml2js\lib\parser.js:324:9)
      at Parser.parseString (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\xml2js\lib\parser.js:6:40)
      at Object.__webpack_modules__.99082.exports.parseString (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\xml2js\lib\parser.js:370:1)
      at C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nuget-plugin\dist\nuget-parser\csproj-parser.js:24:1
      at new Promise (<anonymous>)
      at Object.getTargetFrameworksFromProjFile (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nuget-plugin\dist\nuget-parser\csproj-parser.js:13:1)
      at Object.buildDepTreeFromFiles (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nuget-plugin\dist\nuget-parser\index.js:69:1)
      at Object.inspect (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\node_modules\snyk-nuget-plugin\dist\index.js:59:1)
      at Object.inspect (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\lib\module-info\index.ts:23:13)
      at Object.getSinglePluginResult (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\lib\plugins\get-single-plugin-result.ts:18:21)
      at Object.getDepsFromPlugin (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\lib\plugins\get-deps-from-plugin.ts:105:18)
      at assembleLocalPayloads (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\lib\snyk-test\run-test.ts:572:76)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runTest (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\lib\snyk-test\run-test.ts:339:18)
      at test (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\cli\commands\test\index.ts:93:15)
      at runCommand (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\cli\index.ts:58:25)
      at main (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\cli\index.ts:316:4)
} +0ms
  snyk-test Failed to test 1 projects, errors: +0ms
  snyk-test error: FailedToRunTestError: Cannot read property 'length' of undefined
    at runTest (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\lib\snyk-test\run-test.ts:371:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at test (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\cli\commands\test\index.ts:93:15)
    at runCommand (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\cli\index.ts:58:25)
    at main (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\cli\index.ts:316:4) +1ms
Error:
Testing C:\Git\nextGen\Avary2\Cegal.Platform.Flow\src\Cegal.Core.Immutable...

Cannot read property 'length' of undefined
    at test (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\cli\commands\test\index.ts:241:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runCommand (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\cli\index.ts:58:25)
    at main (C:\Users\robertsc\AppData\Roaming\npm\node_modules\snyk\dist\cli\webpack:\snyk\src\cli\index.ts:316:4)
  snyk Exit code: 2 +0ms
  snyk analytics {
  "args": [
    {
      "dev": true,
      "debug": true
    }
  ],
  "command": "bad-command",
  "metadata": {
    "local": true,
    "error-message": "\nTesting C:\\Git\\nextGen\\Avary2\\Cegal.Platform.Flow\\src\\Cegal.Core.Immutable...\n\nCannot read property 'length' of undefined",
    "error": "Error: \nTesting C:\\Git\\nextGen\\Avary2\\Cegal.Platform.Flow\\src\\Cegal.Core.Immutable...\n\nCannot read property 'length' of undefined\n    at test (C:\\Users\\robertsc\\AppData\\Roaming\\npm\\node_modules\\snyk\\dist\\cli\\webpack:\\snyk\\src\\cli\\commands\\test\\index.ts:241:19)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at runCommand (C:\\Users\\robertsc\\AppData\\Roaming\\npm\\node_modules\\snyk\\dist\\cli\\webpack:\\snyk\\src\\cli\\index.ts:58:25)\n    at main (C:\\Users\\robertsc\\AppData\\Roaming\\npm\\node_modules\\snyk\\dist\\cli\\webpack:\\snyk\\src\\cli\\index.ts:316:4)",
    "error-code": 500,
    "command": "test"
  },
  "os": "Windows 10",
  "version": "1.696.0",
  "nodeVersion": "v14.17.6",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "b724f491e3d0210e32f1dd9ae485d6d382f0cab2",
  "ci": false,
  "environment": {
    "npmVersion": "6.14.15"
  },
  "durationMs": 1801,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [],
      "total": 0
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        1801
      ],
      "total": 1801
    }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1350 +0ms
  snyk gzipped request body size: 606 +0ms
  snyk not using proxy +1ms
```

**Comment by jan-stehlik** [comment]
hey @ugumba , thanks for reporting this bug 👍 . Would you please share the part of your `csproj` file that contains target framework metadata? We would like to implement a fix and make sure it works for your use case. Thanks

**Comment by ugumba** [comment]
So it _works_ with this csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net5.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```
but it _fails_ with this one:
```
<Project Sdk="Microsoft.NET.Sdk">
</Project>
```
when combined with a Directory.Build.props file in the parent directory:
```
<Project>
  <PropertyGroup>
    <TargetFrameworks>net5.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```
which is [supported by MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets).  

Notes:

- a Directory.Build.targets file is also supported.
- In complex solutions, these files may also import further files!

Rather than parsing csproj files and handling complex imports yourself, you may want to look into letting ```msbuild /preprocess``` do that job for you.

**Comment by Havunen** [comment]
Hi!

Same problem occurs if the project uses import to common props where the targetframeworks are defined.

project.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="$(RepositoryRoot)\LibraryProperties.props" />
</Project>
 ```
 
 LibraryProperties.props
 
```
<Project>
  <!-- This file contains common project properties for all library projects -->
  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by Havunen** [comment]
@jan-stehlik 
Is there some reason why snyk needs to read the csproj file for targetFrameworks when it could use the obj/project.assets.json "targets" property

**Comment by Havunen** [comment]
This is actually related to https://github.com/snyk/snyk-nuget-plugin/issues/103

**Comment by Havunen** [comment]
This crash has been fixed in https://github.com/snyk/snyk-nuget-plugin/pull/105
