### ISSUE TITLE
[🐛] "Cannot read property 'digest' of undefined" running snyk on public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6 on Debian 10 (buster)

### ISSUE THREAD

**Issue by dylanlingelbach** [snyk/snyk#2359]
- `node -v`: v12.22.3
- `npm -v`: 6.14.13
- `snyk -v`: 1.760.0
- OS: 
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Command run: 
`snyk container test --severity-threshold=high  public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6`

### Expected behaviour

No error, same output I get when running on Mac OS X

```
snyk container test --severity-threshold=high public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6

Testing public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6...

Organization:      catalyticlabs
Package manager:   rpm
Project name:      docker-image|public.ecr.aws/eks-distro/kubernetes/kube-proxy
Docker image:      public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6
Platform:          linux/amd64
Base image:        amazonlinux:2.0.20211005.0
Local Snyk policy: found
Licenses:          enabled

✔ Tested 145 dependencies for known issues, no vulnerable paths found.

According to our scan, you are currently using the most secure version of the selected base image
```

### Actual behaviour

```
snyk container test --severity-threshold=high public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6
Cannot read property 'digest' of undefined
```

### Steps to reproduce

Run 
```
snyk container test --severity-threshold=high public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6
```

on a Debian 10 OS

### Debug log

```
snyk container test --debug --severity-threshold=high  public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6
  snyk test {
  _: [
    'public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6',
    [Circular]
  ],
  debug: true,
  docker: true,
  experimental: true,
  severityThreshold: 'high'
} +0ms
  snyk public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6 does not exist locally, proceeding to pull image. +0ms
  snyk Attempting to pull: registry: public.ecr.aws, image: eks-distro/kubernetes/kube-proxy, tag: v1.21.2-eks-1-21-6 +74ms
  snyk:run-test Error running test {
  error: TypeError: Cannot read property 'digest' of undefined
      at DockerPull.pull (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/node_modules/@snyk/snyk-docker-pull/dist/docker-pull.js:57:1)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Docker.pull (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/node_modules/snyk-docker-plugin/dist/docker.js:29:1)
      at pullFromContainerRegistry (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/node_modules/snyk-docker-plugin/dist/analyzer/image-inspector.js:67:1)
      at pullImage (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/node_modules/snyk-docker-plugin/dist/analyzer/image-inspector.js:76:1)
      at Object.getImageArchive (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/node_modules/snyk-docker-plugin/dist/analyzer/image-inspector.js:115:1)
      at imageIdentifierAnalysis (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/node_modules/snyk-docker-plugin/dist/scan.js:78:1)
      at Object.assembleEcosystemPayloads (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/snyk-test/assemble-payloads.ts:41:28)
      at runTest (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/snyk-test/run-test.ts:337:22)
      at test (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:93:15)
      at runCommand (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:57:25)
      at main (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:317:11)
} +0ms
  snyk-test Failed to test 1 projects, errors: +0ms
  snyk-test error: FailedToRunTestError: Cannot read property 'digest' of undefined
    at runTest (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/snyk-test/run-test.ts:368:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) +0ms
Error:
Testing public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6...

Cannot read property 'digest' of undefined
    at test (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:241:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  snyk Exit code: 2 +0ms
  snyk analytics {
  "args": [
    "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6",
    {
      "debug": true,
      "docker": true,
      "experimental": true,
      "severityThreshold": "high"
    }
  ],
  "command": "bad-command",
  "metadata": {
    "local": true,
    "error-message": "\nTesting public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6...\n\nCannot read property 'digest' of undefined",
    "error": "Error: \nTesting public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.21.2-eks-1-21-6...\n\nCannot read property 'digest' of undefined\n    at test (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:241:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "error-code": 500,
    "command": "test"
  },
  "os": "Linux 5.10",
  "version": "1.760.0",
  "nodeVersion": "v12.22.3",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "<redacted>",
  "ci": false,
  "environment": {
    "npmVersion": "6.14.13"
  },
  "durationMs": 3472,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [],
      "total": 0
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        3472
      ],
      "total": 3472
    }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1150 +1ms
  snyk gzipped request body size: 579 +0ms
  snyk not using proxy +1ms
```

**Comment by iuliams** [comment]
Issue fixed with version 1.773.0 - https://www.npmjs.com/package/snyk.
