### ISSUE TITLE
[🐛] FileNotFoundError: [Errno 2] No such file or directory: README.md

### ISSUE THREAD

**Issue by mcsage** [snyk/snyk#2491]
- `python setup.py install`:
- OS: OSX 
- Command run: snyk test --json --severity-threshold=low --file=setup.py --command=python3 --debug

### Expected behaviour

snyk test succeeded

### Actual behaviour

snyk test --json --severity-threshold=low --file=setup.py --command=python3 --debug
  snyk test <ref *1> {
  _: [ [Circular *1] ],
  json: true,
  file: 'setup.py',
  command: 'python3',
  debug: true,
  severityThreshold: 'low'
} +0ms
  snyk:run-test Error running test {
  error: 'Traceback (most recent call last):\n' +
    '  File "/var/folders/v1/q18229lx2nsg8y7pwlf2m7pw0000gp/T/tmp-41235-2Gn0ecgmLeNF/pip_resolve.py", line 329, in <module>\n' +
    '    sys.exit(main())\n' +
    '  File "/var/folders/v1/q18229lx2nsg8y7pwlf2m7pw0000gp/T/tmp-41235-2Gn0ecgmLeNF/pip_resolve.py", line 321, in main\n' +
    '    create_dependencies_tree_by_req_file_path(\n' +
    '  File "/var/folders/v1/q18229lx2nsg8y7pwlf2m7pw0000gp/T/tmp-41235-2Gn0ecgmLeNF/pip_resolve.py", line 267, in create_dependencies_tree_by_req_file_path\n' +
    '    required = get_requirements_list(requirements_file_path, dev_deps=dev_deps)\n' +
    '  File "/var/folders/v1/q18229lx2nsg8y7pwlf2m7pw0000gp/T/tmp-41235-2Gn0ecgmLeNF/pip_resolve.py", line 221, in get_requirements_list\n' +
    '    requirements_data = setup_file.parse_requirements(setup_py_file_content)\n' +
    '  File "/private/var/folders/v1/q18229lx2nsg8y7pwlf2m7pw0000gp/T/tmp-41235-2Gn0ecgmLeNF/setup_file.py", line 36, in parse_requirements\n' +
    '    passed_arguments = parse(setup_py_content)\n' +
    '  File "/private/var/folders/v1/q18229lx2nsg8y7pwlf2m7pw0000gp/T/tmp-41235-2Gn0ecgmLeNF/setup_file.py", line 16, in parse\n' +
    '    exec(setup_py_content, globals())\n' +
    '  File "<string>", line 13, in <module>\n' +
    '  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1266, in read_text\n' +
    "    with self.open(mode='r', encoding=encoding, errors=errors) as f:\n" +
    '  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1252, in open\n' +
    '    return io.open(self, mode, buffering, encoding, errors, newline,\n' +
    '  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1120, in _opener\n' +
    '    return self._accessor.open(self, flags, mode)\n' +
    "FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/v1/q18229lx2nsg8y7pwlf2m7pw0000gp/T/tmp-41235-2Gn0ecgmLeNF/README.md'\n"
} +0ms

**Comment by CopernicusPY** [comment]
Try and use 

```py
with open("README.md", "r") as file:
    long_description = file.read()

...
```
