### ISSUE TITLE
`snyk test --dev` throws error

### ISSUE THREAD

**Issue by rankida** [snyk/snyk#282]
- `node -v`: v10.13.0
- `npm -v`: 6.4.1
- `snyk -v`: 1.108.2
- Command run: snyk test --dev

### Expected behaviour
It does not crash and reports any vulnerabilities.

### Actual behaviour
It crashes with:
```
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error:
Testing /Users/davidrankin/dev/nearform/wave2/i18n-ui...

Internal error (reference: 7bf24dac-ffc0-4c1f-bde0-ee389917ca28)
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/cli/commands/test.js:152:23
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Steps to reproduce
On my repo (which I can't share) I get this error when previously it worked fine.
Pure build server also sees this issue
```
12:46:43 An unknown error occurred. Please include the trace below when reporting to Snyk:
12:46:43 
12:46:43 Error: 
12:46:43 Testing /var/lib/jenkins/jobs/wa2.pentest.master.i18n-ui/workspace...
12:46:43 
12:46:43 Internal error (reference: 522ca713-96bc-4e35-bd03-7301a51fea12)
12:46:43     at /var/lib/jenkins/.npm-global/lib/node_modules/snyk/src/cli/commands/test.js:152:23
12:46:43     at process._tickCallback (internal/process/next_tick.js:68:7)
```

Not sure if this is the correct channel to report this issue. Please let me know if I should be using something else.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by rankida** [comment]
`snyk test --dev --debug`
<details><summary>Debug output can be found here</summary>
<p>

```
  snyk test { _: [ [Circular] ], dev: true, debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder /Users/davidrankin/dev/nearform/wave2/i18n-ui +0ms
  snyk found package file package.json in /Users/davidrankin/dev/nearform/wave2/i18n-ui +0ms
  snyk found package file package.json in /Users/davidrankin/dev/nearform/wave2/i18n-ui +60ms
  snyk analytics add local true +0ms
  snyk analytics add using node_modules to get dependency tree true +0ms
  snyk policies found [ '/Users/davidrankin/dev/nearform/wave2/i18n-ui' ] +0ms
  snyk analytics add policies 1 +336ms
  snyk analytics add packageManager npm +1ms
  snyk analytics add packageName @mckinsey/wave-i18n-ui +0ms
  snyk analytics add packageVersion 6.29.0 +0ms
  snyk analytics add package @mckinsey/wave-i18n-ui@6.29.0 +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm +0ms
  snyk request body size: 407963 +0ms
  snyk gzipped request body size: 22264 +0ms
  snyk analytics add payloadSize 407963 +7ms
  snyk analytics add gzippedPayloadSize 22264 +0ms
  snyk not using proxy +1ms
  snyk Failed to test 1 projects, errors: +0ms
  snyk error: Error: Internal error (reference: 24db610f-77e8-4274-95b2-b92871bfbdcd)
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/lib/snyk-test/npm/index.js:219:25
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/lib/request/index.js:12:9
    at process._tickCallback (internal/process/next_tick.js:68:7) +18ms
  snyk analytics add error-message
Testing /Users/davidrankin/dev/nearform/wave2/i18n-ui...

Internal error (reference: 24db610f-77e8-4274-95b2-b92871bfbdcd) +2s
  snyk analytics add error Error:
Testing /Users/davidrankin/dev/nearform/wave2/i18n-ui...

Internal error (reference: 24db610f-77e8-4274-95b2-b92871bfbdcd)
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/cli/commands/test.js:152:23
    at process._tickCallback (internal/process/next_tick.js:68:7) +1ms
  snyk analytics add error-code 422 +0ms
  snyk analytics add command test +0ms
Error:
Testing /Users/davidrankin/dev/nearform/wave2/i18n-ui...

Internal error (reference: 24db610f-77e8-4274-95b2-b92871bfbdcd)
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/cli/commands/test.js:152:23
    at process._tickCallback (internal/process/next_tick.js:68:7)
  snyk analytics { args:
   [ { dev: true, debug: true, org: undefined, showVulnPaths: true } ],
  command: 'bad-command',
  metadata:
   { local: true,
     'using node_modules to get dependency tree': true,
     policies: 1,
     packageManager: 'npm',
     packageName: '@mckinsey/wave-i18n-ui',
     packageVersion: '6.29.0',
     package: '@mckinsey/wave-i18n-ui@6.29.0',
     payloadSize: 407963,
     gzippedPayloadSize: 22264,
     'error-message':
      '\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting /Users/davidrankin/dev/nearform/wave2/i18n-ui...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mInternal error (reference: 24db610f-77e8-4274-95b2-b92871bfbdcd)',
     error:
      'Error: \u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting /Users/davidrankin/dev/nearform/wave2/i18n-ui...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mInternal error (reference: 24db610f-77e8-4274-95b2-b92871bfbdcd)\n    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/cli/commands/test.js:152:23\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     'error-code': 422,
     command: 'test' },
  version: '1.108.2',
  os: 'macOS High Sierra',
  nodeVersion: 'v10.13.0',
  id: '92d25cd63404c41f91150432b04e3a68ad3a73c6',
  ci: false,
  durationMs: 2436 } +1ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +2s
  snyk request body size: 1314 +0ms
  snyk gzipped request body size: 575 +0ms
  snyk not using proxy +0ms
```

</p>
</details>

**Comment by robcresswell** [comment]
Hey @rankida, thanks for this; is it possible for you to try again on the latest version of snyk?

**Comment by rankida** [comment]
Same thing sadly @robcresswell 

```
  master  npm -g i snyk
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
/Users/davidrankin/.nvm/versions/node/v10.13.0/bin/snyk -> /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/dist/cli/index.js
+ snyk@1.111.1
added 4 packages from 4 contributors and updated 6 packages in 22.606s

  master  snyk -v
1.111.1

  master  snyk test --dev
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error:
Testing /Users/davidrankin/dev/nearform/wave2/i18n-ui...

Internal error (reference: 84fd8e7a-a287-4109-8c3a-14fd3da76ba4)
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/cli/commands/test.js:153:23
    at process._tickCallback (internal/process/next_tick.js:68:7)


 ✘   master  snyk test --dev --debug
 ```
 <details><summary>click for full debug log</summary>
 <p>

 ```
  snyk test { _: [ [Circular] ], dev: true, debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder /Users/davidrankin/dev/nearform/wave2/i18n-ui +0ms
  snyk found package file package.json in /Users/davidrankin/dev/nearform/wave2/i18n-ui +1ms
  snyk found package file package.json in /Users/davidrankin/dev/nearform/wave2/i18n-ui +30ms
  snyk analytics add local true +0ms
  snyk analytics add using node_modules to get dependency tree true +0ms
  snyk policies found [ '/Users/davidrankin/dev/nearform/wave2/i18n-ui' ] +0ms
  snyk analytics add policies 1 +376ms
  snyk analytics add packageManager npm +0ms
  snyk analytics add packageName @mckinsey/wave-i18n-ui +0ms
  snyk analytics add packageVersion 6.29.0 +0ms
  snyk analytics add package @mckinsey/wave-i18n-ui@6.29.0 +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm +0ms
  snyk request body size: 407963 +0ms
  snyk gzipped request body size: 22264 +0ms
  snyk analytics add payloadSize 407963 +7ms
  snyk analytics add gzippedPayloadSize 22264 +0ms
  snyk not using proxy +1ms
  snyk Failed to test 1 projects, errors: +0ms
  snyk error: Error: Internal error (reference: 40de6d38-5792-41a5-bd45-40b189e1a04c)
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/lib/snyk-test/npm/index.js:225:25
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/lib/request/index.js:12:9
    at process._tickCallback (internal/process/next_tick.js:68:7) +17ms
  snyk analytics add error-message
Testing /Users/davidrankin/dev/nearform/wave2/i18n-ui...

Internal error (reference: 40de6d38-5792-41a5-bd45-40b189e1a04c) +2s
  snyk analytics add error Error:
Testing /Users/davidrankin/dev/nearform/wave2/i18n-ui...

Internal error (reference: 40de6d38-5792-41a5-bd45-40b189e1a04c)
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/cli/commands/test.js:153:23
    at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
  snyk analytics add error-code 422 +0ms
  snyk analytics add command test +0ms
Error:
Testing /Users/davidrankin/dev/nearform/wave2/i18n-ui...

Internal error (reference: 40de6d38-5792-41a5-bd45-40b189e1a04c)
    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/cli/commands/test.js:153:23
    at process._tickCallback (internal/process/next_tick.js:68:7)
  snyk analytics { args:
   [ { dev: true, debug: true, org: undefined, showVulnPaths: true } ],
  command: 'bad-command',
  metadata:
   { local: true,
     'using node_modules to get dependency tree': true,
     policies: 1,
     packageManager: 'npm',
     packageName: '@mckinsey/wave-i18n-ui',
     packageVersion: '6.29.0',
     package: '@mckinsey/wave-i18n-ui@6.29.0',
     payloadSize: 407963,
     gzippedPayloadSize: 22264,
     'error-message':
      '\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting /Users/davidrankin/dev/nearform/wave2/i18n-ui...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mInternal error (reference: 40de6d38-5792-41a5-bd45-40b189e1a04c)',
     error:
      'Error: \u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting /Users/davidrankin/dev/nearform/wave2/i18n-ui...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mInternal error (reference: 40de6d38-5792-41a5-bd45-40b189e1a04c)\n    at /Users/davidrankin/.nvm/versions/node/v10.13.0/lib/node_modules/snyk/src/cli/commands/test.js:153:23\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     'error-code': 422,
     command: 'test' },
  version: '1.111.1',
  os: 'macOS High Sierra',
  nodeVersion: 'v10.13.0',
  id: '8925976e333b78cf1cb096a30cd12e0984de7dd9',
  ci: false,
  durationMs: 2149 } +2ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +2s
  snyk request body size: 1314 +0ms
  snyk gzipped request body size: 573 +0ms
  snyk not using proxy +0ms
  ```

  </p></details>

**Comment by michael-go** [comment]
Hi @rankida - thanks for reporting! we identified the issue. Seems it's caused by a funky dependency tree where the root package is also a dependency by itself (cycle with root...).
We are looking into it - sorry for the incontinence 🙏

**Comment by michael-go** [comment]
@rankida :wave: I hope we addressed the issue in the back-end - can you try again please? 🙇

**Comment by rankida** [comment]
It is now working again for me. Thanks!
