### ISSUE TITLE
Inconsistent errors regarding an existing virtualenv when running `snyk test` in python3.7 project:

### ISSUE THREAD

**Issue by dopatraman** [snyk/snyk#334]
- `node -v`: v11.6.0
- `npm -v`: 6.5.0-next.0
- `snyk -v`: 1.122.0
- Command run: snyk test

### Expected behaviour
I assume snyk should run as expected and check vulnerabilities without error.

### Actual behaviour
```
Creating a virtualenv for this project…
Pipfile: /Pipfile
Using /usr/local/bin/python (3.7.1) to create virtualenv…
⠋ Creating virtual environment...Already using interpreter /usr/local/bin/python
Using base prefix '/usr/local'

✘ Failed creating virtual environment 
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 408, in run
[pipenv.exceptions.VirtualenvCreationException]:       command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2310, in do_run
[pipenv.exceptions.VirtualenvCreationException]:       three=three, python=python, validate=False, pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 2438, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 768, in main
    symlink=options.symlink,
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1013, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1214, in install_python
    mkdir(lib_dir)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 382, in mkdir
    os.makedirs(at_path)
  File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.7'

Failed to create virtual environment.


The command '/bin/sh -c snyk test' returned a non-zero code: 1
```

This seems to indicate that snyk creates a virtualenv that is problematic.

### Steps to reproduce
Run `snyk test` with the versions of python (3.7) and node above.

**Comment by lili2311** [comment]
👋 Just to keep you updated, we are investigating this issue. Will get back to you soon to share what we found.

**Comment by lili2311** [comment]
Replied in the case, please take a look there.
