### ISSUE TITLE
An unknown error occurred. Please include the trace below when reporting to Snyk...

### ISSUE THREAD

**Issue by dep** [snyk/snyk#357]
- `node -v`: v8.11.1
- `npm -v`: 5.6.0
- `snyk -v`: 1.78.1
- Command run: `snyk test`

### Expected behaviour

completes without error

### Actual behaviour

```
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: 413
    at /Users/<username>/.config/yarn/global/node_modules/snyk/cli/commands/test.js:134:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Steps to reproduce

1. Run `snyk test`

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

```
▶ snyk test --debug
  snyk test { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder /Users/username/Sites/enterprise-web +0ms
  snyk trying to autodetect for yarn.lock +1ms
  snyk analytics add local true +0ms
/ Analyzing npm dependencies for package.json
  snyk policies found [ '/Users/username/Sites/enterprise-web',
  '/Users/username/Sites/enterprise-web/node_modules/@enterprise/api-proxy-middleware',
  '/Users/username/Sites/enterprise-web/node_modules/@enterprise/enterprise-icons',
  '/Users/username/Sites/enterprise-web/node_modules/@enterprise/enterprise-regression-tests',
  '/Users/username/Sites/enterprise-web/node_modules/@enterprise/enterprise-ui',
  '/Users/username/Sites/enterprise-web/node_modules/@enterprise/enterprise-ui-middleware',
  '/Users/username/Sites/enterprise-web/node_modules/@enterprise/enterprise-web' ] +0ms
  snyk analytics add policies 7 +3m
  snyk analytics add packageManager npm +194ms
  snyk analytics add packageName enterprise-web +0ms
  snyk analytics add packageVersion null +0ms
  snyk analytics add package enterprise-web@null +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm +0ms
  snyk request body size: 59725044 +0ms
  snyk analytics add payloadSize 59725044 +872ms
  snyk not using proxy +1ms
  snyk analytics add error-message 413 +2s
  snyk analytics add error Error: 413
    at /Users/username/.config/yarn/global/node_modules/snyk/cli/commands/test.js:134:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) +0ms
  snyk analytics add error-code 413 +1ms
  snyk analytics add command test +0ms
Error: 413
    at /Users/username/.config/yarn/global/node_modules/snyk/cli/commands/test.js:134:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  snyk analytics { command: 'bad-command',
  args: [ { debug: true, org: undefined, showVulnPaths: true } ],
  metadata:
   { local: true,
     policies: 7,
     packageManager: 'npm',
     packageName: 'enterprise-web',
     packageVersion: null,
     package: 'enterprise-web@null',
     payloadSize: 59725044,
     'error-message': '413',
     error: 'Error: 413\n    at /Users/username/.config/yarn/global/node_modules/snyk/cli/commands/test.js:134:21\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
     'error-code': 413,
     command: 'test' },
  version: '1.78.1',
  os: 'macOS',
  nodeVersion: 'v8.11.1',
  id: 'c2d1d3a266e99d17b0905090a54ceeece840ac7b',
  ci: false,
  durationMs: 194562 } +1ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +2s
  snyk request body size: 638 +0ms
  snyk not using proxy +0ms
```

**Comment by adrukh** [comment]
@dep please upgrade your version of `snyk`. We've implemented quite a few performance improvements since the version you are using.

Please post the same debug info from a new version if this persists.

**Comment by adrukh** [comment]
@dep I'm going to close this issue for now. Please reopen if this happens again!
