### ISSUE TITLE
snyk test command with `npm link`ed modules.

### ISSUE THREAD

**Issue by hanjukim** [Snyk/snyk#39]
- `node -v`: v6.4.0
- `npm -v`: 3.10.6
- `snyk -v`: 1.18.1
- OS: OS X El Capitan 10.11.6 (15G31)
- Command run:
  ./node_modules/.bin/snyk test
### Expected behaviour

command should finish without errors.
### Actual behaviour

An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: 504
    at /Users/hanjukim/styleket/libre-api-server/node_modules/snyk/lib/test.js:104:23
    at /Users/hanjukim/styleket/libre-api-server/node_modules/snyk/lib/request.js:64:7
    at lib$es6$promise$$internal$$tryCatch (/Users/hanjukim/styleket/libre-api-server/node_modules/es6-promise/dist/es6-promise.js:362:16)
    at lib$es6$promise$$internal$$invokeCallback (/Users/hanjukim/styleket/libre-api-server/node_modules/es6-promise/dist/es6-promise.js:374:17)
    at lib$es6$promise$$internal$$publish (/Users/hanjukim/styleket/libre-api-server/node_modules/es6-promise/dist/es6-promise.js:345:11)
    at lib$es6$promise$asap$$flush (/Users/hanjukim/styleket/libre-api-server/node_modules/es6-promise/dist/es6-promise.js:119:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
### Actual behaviour 2

An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: unexpected error: undefined
    at /Users/hanjukim/styleket/libre-api-server/node_modules/snyk/lib/monitor.js:54:21
    at /Users/hanjukim/styleket/libre-api-server/node_modules/snyk/lib/request.js:64:7
    at lib$es6$promise$$internal$$tryCatch (/Users/hanjukim/styleket/libre-api-server/node_modules/es6-promise/dist/es6-promise.js:362:16)
    at lib$es6$promise$$internal$$invokeCallback (/Users/hanjukim/styleket/libre-api-server/node_modules/es6-promise/dist/es6-promise.js:374:17)
    at lib$es6$promise$$internal$$publish (/Users/hanjukim/styleket/libre-api-server/node_modules/es6-promise/dist/es6-promise.js:345:11)
    at lib$es6$promise$asap$$flush (/Users/hanjukim/styleket/libre-api-server/node_modules/es6-promise/dist/es6-promise.js:119:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
### Steps to reproduce
1. npm link in <module> directory
2. npm link <module> in `snyk`ed module.
3. snyk test
---

I had to `npm link` 3 private modules to reproduce error, and sometimes `snyk test` finish without error. I guess there's some kind of recursive behaviour when `npm link`ed module with its own node_modules exists. I use `npm link` command in development only.

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by Eruant** [comment]
I've had a similar error to this, but I've not had any `npm linked` apps in my application.

```
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: 504
    at /.../node_modules/snyk/lib/test.js:104:23
    at /.../node_modules/snyk/lib/request.js:64:7
    at lib$es6$promise$$internal$$tryCatch (/.../node_modules/es6-promise/dist/es6-promise.js:362:16)
    at lib$es6$promise$$internal$$invokeCallback (/.../node_modules/es6-promise/dist/es6-promise.js:374:17)
    at lib$es6$promise$$internal$$publish (/.../node_modules/es6-promise/dist/es6-promise.js:345:11)
    at lib$es6$promise$asap$$flush (/.../node_modules/es6-promise/dist/es6-promise.js:119:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by guypod** [comment]
@eruant can you share your `Package.json` file, either here or by mailing it to support@snyk.io?

**Comment by Eruant** [comment]
The 504 error seems to have resolved itself now.

**Comment by hanjukim** [comment]
For me, it's not resolved yet.
