### ISSUE TITLE
running multiple instances in parallel throws

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#479]
- `node -v`:v10.15.3
- `npm -v`: 6.9.0
- `snyk -v`: 1.161.1

```
C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd test "--file=C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\package-lock.json"
C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd test "--file=C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\package.json"
```

### Expected behaviour
Runs without issues

### Actual behaviour
Throws
```
##vso[task.debug]result: 0
##vso[task.debug]Calling snyk test...
##vso[task.debug]which 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
##vso[task.debug]found: 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
##vso[task.debug]which 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
##vso[task.debug]found: 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
[command]C:\WINDOWS\system32\cmd.exe /D /S /C "C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd test "--file=C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\package-lock.json""
##vso[task.debug]Calling snyk test...
##vso[task.debug]which 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
##vso[task.debug]found: 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
##vso[task.debug]which 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
##vso[task.debug]found: 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
[command]C:\WINDOWS\system32\cmd.exe /D /S /C "C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd test "--file=C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\package.json""
Error: EBADF: bad file descriptor, close
    at Object.closeSync (fs.js:409:3)
    at Object.closeSync (C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\graceful-fs\graceful-fs.js:52:27)
    at Function.writeFileSync [as sync] (C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\write-file-atomic\index.js:228:16)
    at Configstore.set all [as all] (C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\configstore\index.js:58:20)
    at new Configstore (C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\configstore\index.js:25:12)
    at Object.<anonymous> (C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\snyk\src\lib\user-config.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
##vso[task.debug]result: 1
##vso[task.issue type=warning;]Snyk reported one or more issues. Ignoring due to 'Fail Build = false'.
##vso[task.debug]Calling snyk monitor...
##vso[task.debug]which 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
##vso[task.debug]found: 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
##vso[task.debug]which 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
##vso[task.debug]found: 'C:\Users\JesseHouwing\source\repos\vsts-snyk-task\snyk\node_modules\.bin\snyk.cmd'
```

### Steps to reproduce

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
👋 @jessehouwing is this still an issue for you? Does `--all-projects` remove the need for running in parallel?

**Comment by jessehouwing** [comment]
I haven't tried. I can imagine that when we run snyk on a build server with
multiple agents, this issue may still occur. Many folks in the .NET world
have one or more agents on a persistent VM/IaaS machine. With the Azure
DevOps task installing Snyk globally, I suppose this is still a thing.
