### ISSUE TITLE
Snyk test throws: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#481]
- `node -v`: v10.15.0
- `npm -v`: 6.9.0
- `snyk -v`:1.161.1
- Command run:
```
snyk test PartsUnlimited.sln
```

### Expected behaviour
Gives a nice error message to tell me I should use `--file=`.

### Actual behaviour
```
Cannot read property 'endsWith' of undefined
```

### Steps to reproduce

---
```
C:\Users\jesse\Source\Repos\PartsUnlimited>snyk test PartsUnlimited.sln --debug
  snyk test { _: [ 'PartsUnlimited.sln', [Circular] ], debug: true } +0ms
  snyk specified paramater is not a folder, trying to lookup as repo +0ms
  snyk no package file found in PartsUnlimited.sln +6ms
  snyk Failed to test 1 projects, errors: +0ms
  snyk error: TypeError: Cannot read property 'endsWith' of undefined
    at Promise.resolve.then (C:\Users\jesse\AppData\Roaming\npm\node_modules\snyk\src\lib\snyk-test\npm\index.js:62:47)
    at process._tickCallback (internal/process/next_tick.js:68:7) +15ms
  snyk analytics add error-message
Testing PartsUnlimited.sln...

Cannot read property 'endsWith' of undefined +0ms
  snyk analytics add error Error:
Testing PartsUnlimited.sln...

Cannot read property 'endsWith' of undefined
    at C:\Users\jesse\AppData\Roaming\npm\node_modules\snyk\src\cli\commands\test.ts:160:19
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\jesse\AppData\Roaming\npm\node_modules\snyk\dist\cli\commands\test.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
  snyk analytics add error-code undefined +2ms
  snyk analytics add command test +0ms
Error:
Testing PartsUnlimited.sln...

Cannot read property 'endsWith' of undefined
    at C:\Users\jesse\AppData\Roaming\npm\node_modules\snyk\src\cli\commands\test.ts:160:19
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\jesse\AppData\Roaming\npm\node_modules\snyk\dist\cli\commands\test.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  snyk analytics { args:
   [ 'PartsUnlimited.sln',
     { debug: true, org: undefined, showVulnPaths: true } ],
  command: 'bad-command',
  metadata:
   { 'error-message':
      '\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting PartsUnlimited.sln...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mCannot read property \'endsWith\' of undefined',
     error:
      'Error: \u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting PartsUnlimited.sln...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mCannot read property \'endsWith\' of undefined\n    at C:\\Users\\jesse\\AppData\\Roaming\\npm\\node_modules\\snyk\\src\\cli\\commands\\test.ts:160:19\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\jesse\\AppData\\Roaming\\npm\\node_modules\\snyk\\dist\\cli\\commands\\test.js:5:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     'error-code': undefined,
     command: 'test' },
  version: '1.161.1',
  os: 'Windows 10',
  nodeVersion: 'v10.15.0',
  id: '17ad97d808eb9c6592e1b491fb080d1aae9b7ee7',
  ci: false,
  durationMs: 315 } +239ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1099 +1ms
  snyk gzipped request body size: 473 +0ms
  snyk not using proxy +2ms
```

**Comment by lili2311** [comment]
👋 Does the issue also occur with the latest version of the CLI?

**Comment by jessehouwing** [comment]
```
C:\Users\JesseHouwing\source\repos\PU>npm install snyk -g
C:\Users\JesseHouwing\AppData\Roaming\npm\snyk -> C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js
+ snyk@1.163.3
added 7 packages from 2 contributors and updated 5 packages in 16.163s

C:\Users\JesseHouwing\source\repos\PU>snyk test PartsUnlimited.sln

Testing PartsUnlimited.sln...

Cannot read property 'endsWith' of undefined


C:\Users\JesseHouwing\source\repos\PU>
```

**Comment by lili2311** [comment]
Thank you, what files are present in `PartsUnlimited.sln`? Looks like we did not detect any we support and then did not throw a nice message.

**Comment by jessehouwing** [comment]
https://github.com/jessehouwing/PartsUnlimited

**Comment by lili2311** [comment]
👋 Merged an improvement to give better error message when no supported project files are found while scanning SLN.

Looking at part 2 now to give a better error if `--file` is missing for SLN

**Comment by lili2311** [comment]
Both changes now released, please try again with the latest version of CLI. Should be a better message now
