### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by Benson666** [snyk/snyk#497]
- `node -v`: v8.12.0
- `npm -v`:6.4.1
- `snyk -v`: 1.163.0
- Command run:    snyk test

I run this command on a internal linux server which can only be networked through HTTP(S) proxy. I have set SNYK_TOKEN which can work on a unlimited server.

But it Prompts error:

An unknown error occurred. Please include the trace below when reporting to Snyk:

Error:
Testing /root/kibana-6.5.1-linux-x86_64...

unable to verify the first certificate
    at /usr/local/node/lib/node_modules/snyk/src/cli/commands/test.ts:160:19
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/node/lib/node_modules/snyk/dist/cli/commands/test.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

### Steps to reproduce

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by bartenbach** [comment]
Never good to end up on an issue that's several years old with no replies.

Same setup, same problem.

**Comment by bartenbach** [comment]
Wait, isn't this the solution? https://support.snyk.io/hc/en-us/articles/360002618657-Unable-to-get-Issuer-Certificates-Locally

**Comment by bartenbach** [comment]
Can confirm.  Passing `--insecure` resolves the issue.

Recommend closing.
