### ISSUE TITLE
Error when specifying Dockerfile path with `--file` for `test` and `monitor`

### ISSUE THREAD

**Issue by garethr** [snyk/snyk#505]
- `node -v`: v10.15.3
- `npm -v`: 6.4.1
- `snyk -v`: 1.164.1

```powershell
[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18362  0
```

### Expected behaviour

That it would be possible to specify the Dockerfile location when testing/monitoring a Docker image.

### Actual behaviour

```console
$ snyk monitor --docker garethr/flasky --file ./Dockerfile
super fail TypeError: args.options.file.match is not a function
    at C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\src\cli\index.ts:115:46
    at step (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:33:23)
    at Object.next (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:14:53)
    at C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:4:12)
    at main (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:153:12)
    at Object.<anonymous> (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\src\cli\index.ts:141:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

With debug

```console
$ snyk test --docker garethr/flasky --file Dockerfile --debug
  snyk test { _: [ 'garethr/flasky', 'Dockerfile', [Circular] ],
  docker: true,
  file: true,
  debug: true } +0ms
super fail TypeError: args.options.file.match is not a function
    at C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\src\cli\index.ts:115:46
    at step (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:33:23)
    at Object.next (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:14:53)
    at C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:4:12)
    at main (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:153:12)
    at Object.<anonymous> (C:\Users\garet\AppData\Roaming\npm\node_modules\snyk\src\cli\index.ts:141:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

I receive the same error when running with `test`, rather than `monitor` as well.

The `snyk monitor --help` information leads me to believe this should work:

```console
$ snyk test --docker myapp:latest --file=./myapp/Dockerfile
```

### Steps to reproduce

```
git clone https://github.com/garethr/flasky.git
cd flasky
docker build -t garethr/flasky
snyk test --docker garethr/flasky --file Dockerfile --debug
```

**Comment by adrukh** [comment]
Not the most intuitive decision on our behalf, but `--file` needs to be followed by a `=`

**Comment by garethr** [comment]
Ah, that does work. Thanks. Providing an error message, or better yet improving the UI, would be good.

**Comment by adrukh** [comment]
Truth is it is the `--docker` flag that is Boolean in nature, and doesn’t use a `=`. See if our docs can benefit from this clarification, maybe submit a PR?

**Comment by lili2311** [comment]
We have released an improvement, so you should now see:
`Empty --file argument. Did you mean --file=path/to/file ?` as the message.
