### ISSUE TITLE
Snyk protect throws unhandled exception on Travis build in snyk-test/run-test.ts

### ISSUE THREAD

**Issue by klivin** [snyk/snyk#521]
$ node --version
v10.15.3
$ npm --version
6.4.1
$ nvm --version
0.34.0
$ yarn --version
1.15.2
- `snyk -v`:
version: v1.13.3

- Command run:
sync protect 

### Expected behaviour
Travis builds would succeed like local builds

### Actual behaviour
Travis errors out running sync protect with:
```
> @xyo-network/dapp-scsc-solidity@1.1.3 snyk-protect /home/travis/build/XYOracleNetwork/dapp-scsc-solidity
> snyk protect
An unknown error occurred. Please include the trace below when reporting to Snyk:
Error: 413
    at request (/home/travis/build/XYOracleNetwork/dapp-scsc-solidity/node_modules/snyk/src/lib/snyk-test/run-test.ts:150:21)
    at /home/travis/build/XYOracleNetwork/dapp-scsc-solidity/node_modules/snyk/src/lib/request/index.js:12:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @xyo-network/dapp-scsc-solidity@1.1.3 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @xyo-network/dapp-scsc-solidity@1.1.3 snyk-protect script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-05-15T16_25_21_627Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Steps to reproduce
On merging a PR with Sync added to project, this will cause the Travis auto build to kick off and fail with unhandled error.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

Here is debug output:
```
> @xyo-network/dapp-scsc-solidity@1.1.3 snyk-protect /home/travis/build/XYOracleNetwork/dapp-scsc-solidity
> snyk protect --debug
  snyk protect { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder /home/travis/build/XYOracleNetwork/dapp-scsc-solidity +0ms
  snyk found package file yarn.lock in /home/travis/build/XYOracleNetwork/dapp-scsc-solidity +0ms
  snyk ~~~~ LIVE RUN ~~~~ +0ms
  snyk no file specified. Trying to autodetect in base folder /home/travis/build/XYOracleNetwork/dapp-scsc-solidity +9ms
  snyk found package file yarn.lock in /home/travis/build/XYOracleNetwork/dapp-scsc-solidity +0ms
  snyk analytics add local true +0ms
  snyk found package file yarn.lock in /home/travis/build/XYOracleNetwork/dapp-scsc-solidity +2ms
  snyk calling plugin inspect() { root: '/home/travis/build/XYOracleNetwork/dapp-scsc-solidity',
  targetFile: 'yarn.lock',
  pluginOptions:
   { args: undefined,
     _: [ [Object] ],
     debug: true,
     loose: true,
     vulnEndpoint: '/vuln/npm/patches',
     traverseNodeModules: true,
     packageManager: 'yarn',
     file: 'yarn.lock' } } +0ms
  snyk analytics add local true +4ms
  snyk analytics add generating-node-dependency-tree { lockFile: false, targetFile: 'yarn.lock' } +0ms
  snyk plugin inspect() done +1m
  snyk policies found [ '/home/travis/build/XYOracleNetwork/dapp-scsc-solidity',
  '/home/travis/build/XYOracleNetwork/dapp-scsc-solidity/node_modules/snyk' ] +0ms
  snyk analytics add policies 2 +1m
  snyk analytics add packageManager npm +0ms
  snyk analytics add packageName @xyo-network/dapp-scsc-solidity +0ms
  snyk analytics add packageVersion 1.1.3 +0ms
  snyk analytics add package @xyo-network/dapp-scsc-solidity@1.1.3 +1ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm/patches +0ms
  snyk request body size: 158724691 +1ms
  snyk gzipped request body size: 8903445 +0ms
  snyk analytics add payloadSize 158724691 +8s
  snyk analytics add gzippedPayloadSize 8903445 +0ms
  snyk not using proxy +2s
  snyk analytics add success false +6s
  snyk analytics add error-message 413 +29ms
  snyk analytics add error Error: 413
    at request (/home/travis/build/XYOracleNetwork/dapp-scsc-solidity/node_modules/snyk/src/lib/snyk-test/run-test.ts:150:21)
    at /home/travis/build/XYOracleNetwork/dapp-scsc-solidity/node_modules/snyk/src/lib/request/index.js:12:9
    at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
  snyk analytics add error-code 413 +0ms
  snyk analytics add command protect +0ms
Error: 413
    at request (/home/travis/build/XYOracleNetwork/dapp-scsc-solidity/node_modules/snyk/src/lib/snyk-test/run-test.ts:150:21)
    at /home/travis/build/XYOracleNetwork/dapp-scsc-solidity/node_modules/snyk/src/lib/request/index.js:12:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
  snyk analytics { args:
   [ { debug: true,
       loose: true,
       vulnEndpoint: '/vuln/npm/patches',
       traverseNodeModules: true,
       packageManager: 'yarn',
       file: 'yarn.lock' } ],
  command: 'bad-command',
  metadata:
   { local: [ true, true ],
     'generating-node-dependency-tree': { lockFile: false, targetFile: 'yarn.lock' },
     policies: 2,
     packageManager: 'npm',
     packageName: '@xyo-network/dapp-scsc-solidity',
     packageVersion: '1.1.3',
     package: '@xyo-network/dapp-scsc-solidity@1.1.3',
     payloadSize: 158724691,
     gzippedPayloadSize: 8903445,
     success: false,
     'error-message': '413',
     error:
      'Error: 413\n    at request (/home/travis/build/XYOracleNetwork/dapp-scsc-solidity/node_modules/snyk/src/lib/snyk-test/run-test.ts:150:21)\n    at /home/travis/build/XYOracleNetwork/dapp-scsc-solidity/node_modules/snyk/src/lib/request/index.js:12:9\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     'error-code': 413,
     command: 'protect' },
  version: '1.164.0',
  os: 'Linux 4.15',
  nodeVersion: 'v10.15.3',
  id: '0614b92611c8495796f604ed854b8a9dddfc2c36',
  ci: true,
  durationMs: 100717 } +3ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +4s
  snyk request body size: 1040 +0ms
  snyk gzipped request body size: 562 +0ms
  snyk not using proxy +1ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @xyo-network/dapp-scsc-solidity@1.1.3 snyk-protect: `snyk protect --debug`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @xyo-network/dapp-scsc-solidity@1.1.3 snyk-protect script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-05-15T16_40_37_099Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by lili2311** [comment]
👋 Sorry to hear it's not working, is it consistent?
Would you be able to share your `yarn.lock` + `package.json` for us to replicate this problem?

**Comment by klivin** [comment]
Hi, sure, here are the files:
[package copy.txt](https://github.com/snyk/snyk/files/3184191/package.copy.txt)
[yarn.lock copy.txt](https://github.com/snyk/snyk/files/3184194/yarn.lock.copy.txt)

Snyk test runs ok and the Snyk protect works well locally. 
Someone mentioned maybe the issue is that if NVM it's used, yarn runs on the global node version and the build runs on a local one, or the other way around?

**Comment by Ryuno-Ki** [comment]
Affects me in https://github.com/Ryuno-Ki/eleventy-filter-npm-package-downloads/issues/15 as well.

```txt
# ~/.npm/_logs/2019-05-15T22_16_57_254Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '$HOME/.nvm/versions/node/v11.0.0/bin/node',
1 verbose cli   '$HOME/.nvm/versions/node/v11.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'snyk-protect' ]
2 info using npm@6.9.0
3 info using node@v11.0.0
4 verbose run-script [ 'presnyk-protect', 'snyk-protect', 'postsnyk-protect' ]
5 info lifecycle eleventy-filter-npm-package-downloads@0.1.1~presnyk-protect: eleventy-filter-npm-package-downloads@0.1.1
6 info lifecycle eleventy-filter-npm-package-downloads@0.1.1~snyk-protect: eleventy-filter-npm-package-downloads@0.1.1
7 verbose lifecycle eleventy-filter-npm-package-downloads@0.1.1~snyk-protect: unsafe-perm in lifecycle true
8 verbose lifecycle eleventy-filter-npm-package-downloads@0.1.1~snyk-protect: PATH: $HOME/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:$HOME/src/eleventy-filter-npm-package-downloads/node_modules/.bin:$HOME/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:$HOME/src/eleventy-filter-npm-package-downloads/node_modules/.bin:$HOME/.nvm/versions/node/v11.0.0/bin:/usr/lib/llvm/8/bin:/usr/lib/llvm/7/bin:/usr/lib/llvm/6/bin:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/games/bin:/home/andrej/bin:$HOME/bin:/home/andrej/.vim/pack/bundle/start/fzf/bin
9 verbose lifecycle eleventy-filter-npm-package-downloads@0.1.1~snyk-protect: CWD: /home/andrej/src/eleventy-filter-npm-package-downloads
10 silly lifecycle eleventy-filter-npm-package-downloads@0.1.1~snyk-protect: Args: [ '-c', 'snyk protect' ]
11 silly lifecycle eleventy-filter-npm-package-downloads@0.1.1~snyk-protect: Returned: code: 1  signal: null
12 info lifecycle eleventy-filter-npm-package-downloads@0.1.1~snyk-protect: Failed to exec snyk-protect script
13 verbose stack Error: eleventy-filter-npm-package-downloads@0.1.1 snyk-protect: `snyk protect`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> ($HOME/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/andrej/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid eleventy-filter-npm-package-downloads@0.1.1
15 verbose cwd $HOME/src/eleventy-filter-npm-package-downloads
16 verbose Linux 5.0.0-sabayon
17 verbose argv "$HOME/.nvm/versions/node/v11.0.0/bin/node" "$HOME/.nvm/versions/node/v11.0.0/bin/npm" "run" "snyk-protect"
18 verbose node v11.0.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error eleventy-filter-npm-package-downloads@0.1.1 snyk-protect: `snyk protect`
22 error Exit status 1
23 error Failed at the eleventy-filter-npm-package-downloads@0.1.1 snyk-protect script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

For the record:

```sh
node --version  # v11.0.0
npm --version  # 6.9.0 (no yarn in use)
nvm --version  # 0.34.0
snyk --version  # 1.163.0 (installed locally)
```

Feel welcome to fork my repo and play around.

https://github.com/Ryuno-Ki/eleventy-filter-npm-package-downloads/commit/0123a560dd49c6f79f46f980dc7af184377f676d is the commit which touched `snyk` last.
Introduced by https://github.com/Ryuno-Ki/eleventy-filter-npm-package-downloads/pull/11

**Comment by lili2311** [comment]
Thank you! Will take a deeper look. The first we notice is that the number of dependencies is huge and we will struggle with that.

We have recently made improvements to test that generate smaller payloads, but this is a route that is not yet optimized like that. Will see what we can do to help here, perhaps we can lean on similar improvements.

**Comment by lili2311** [comment]
So I tried this localy and snyk is OK with applying pacthes localy:

```
$ npm run snyk-protect
> @xyo-network/dapp-scsc-solidity@1.1.3 snyk-protect /Users/lili/www/snyk/oncall/dapp-scsc-solidity
> snyk protect

Successfully applied Snyk patches

✨  Done in 286.07s.```

Are you seeing it works locally but not in Travis?

**Comment by klivin** [comment]
Yes, it runs locally fine, and if fails only on Travis.  Here is the Travis build failure:
https://travis-ci.com/XYOracleNetwork/dapp-scsc-solidity/jobs/200501480

**Comment by lili2311** [comment]
Have you already tried clearing the Travis PR cache and see if that helps at all?

**Comment by lili2311** [comment]
@klivin did you get a chance to try clearing the cache? Is this still an issue?

**Comment by lili2311** [comment]
Closing, please re-open if needed.
