### ISSUE TITLE
Can't global install

### ISSUE THREAD

**Issue by asherzog** [snyk/snyk#525]
- `node -v`: v8.6.0
- `npm -v`: 5.6.0
- `snyk -v`: N/A
- Command run: `npm i -g snyk`

-`npm config get registry`:  https://registry.npmjs.org/

### Expected behaviour
Installs Snyk

### Actual behaviour
```
npm ERR! code E404
npm ERR! 404 Not Found: @snyk/dep-graph@1.4.1
npm ERR! 404 Not Found: @snyk/gemfile@1.2.0
```

```
108 http fetch GET 304 https://registry.npmjs.org/snyk-tree 72ms (from cache)
109 silly pacote range manifest for snyk-tree@^1.0.0 fetched in 73ms
110 silly resolveWithNewModule snyk-tree@1.0.0 checking installable status
111 http fetch GET 304 https://registry.npmjs.org/tempfile 58ms (from cache)
112 http fetch GET 304 https://registry.npmjs.org/source-map-support 64ms (from cache)
113 silly pacote range manifest for tempfile@^2.0.0 fetched in 59ms
114 silly resolveWithNewModule tempfile@2.0.0 checking installable status
115 silly pacote range manifest for source-map-support@^0.5.11 fetched in 65ms
116 silly resolveWithNewModule source-map-support@0.5.12 checking installable status
117 http fetch GET 304 https://registry.npmjs.org/then-fs 49ms (from cache)
118 silly pacote range manifest for then-fs@^2.0.0 fetched in 50ms
119 silly resolveWithNewModule then-fs@2.0.0 checking installable status
120 http fetch GET 304 https://registry.npmjs.org/os-name 307ms (from cache)
121 silly pacote range manifest for os-name@^3.0.0 fetched in 308ms
122 silly resolveWithNewModule os-name@3.1.0 checking installable status
123 http fetch GET 304 https://registry.npmjs.org/uuid 53ms (from cache)
124 silly pacote range manifest for uuid@^3.3.2 fetched in 54ms
125 silly resolveWithNewModule uuid@3.3.2 checking installable status
126 http fetch GET 304 https://registry.npmjs.org/update-notifier 71ms (from cache)
127 silly pacote range manifest for update-notifier@^2.5.0 fetched in 72ms
128 silly resolveWithNewModule update-notifier@2.5.0 checking installable status
129 verbose stack Error: 404 Not Found: @snyk/dep-graph@1.4.1
129 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
129 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
129 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
129 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
129 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
129 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
129 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
129 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
129 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
129 verbose stack     at runCallback (timers.js:781:20)
129 verbose stack     at tryOnImmediate (timers.js:743:5)
129 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
```

### Steps to reproduce
run `npm i -g snyk`

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
👋 We have tried to replicate this issue locally and are unable to do so. Is this happenning consistently for you?

**Comment by asherzog** [comment]
Not sure entirely why, but deleting my `.npmrc` resolved the issue.
