### ISSUE TITLE
not working with pnpm

### ISSUE THREAD

**Issue by dcaillibaud** [snyk/snyk#667]
- `node -v`: v10.16.0
- `pnpm -v`: 3.6.0
- `snyk -v`: 1.193.3
- Command run:
snyk protect

### Expected behaviour

Having a normal output

### Actual behaviour

```
Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (node_modules/.registry.npmjs.org/snyk-sbt-plugin/2.5.6/node_modules/snyk-sbt-plugin/dist/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Steps to reproduce

```
# if pnpm not already installed
npm i -g pnpm
# then
mkdir snyktest
cd snyktest
echo '{"dependencies": {"snyk": "^1.193.3"}}' > package.json
pnpm i
./node_modules/.bin/snyk
```

=> show the error above

I guess it's because the module snyk-sbt-plugin is usinq a package (tslib) without mentionning it in its package.json

**Comment by darmalovan** [comment]
Thanks for reaching out!

Will try to add `tslib` to the sbt plugin, and see if it solves the issue!
