### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by elliottsj** [Snyk/snyk#7]
Getting this error, tried both v1.7.0 and v1.6.1:
```
❯ snyk wizard

Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

Loading dependencies...
Cannot read property 'replace' of undefined
```

Happens with `snyk test` too:
```
❯ snyk test         
Cannot read property 'replace' of undefined
```

Using `--debug` flag on v1.7.0:
```
❯ snyk test --debug                                                                     
  snyk test +0ms { _: [ [Circular] ], debug: true }
  snyk checking for cli updates +535ms
  snyk policies found +612ms [ '(redacted)' ]
  snyk compressing body (138369) +3ms
  snyk request payload:  +1ms {"url":"https://snyk.io/api/v1/vuln/npm","json":true,"headers":{"x-is-ci":false,"authorization":"token (redacted)","content-encoding":"gzip"},"method":"POST"}
  snyk null +462msbilities database...
  snyk response (500):  +1ms {"message":"Cannot read property 'replace' of undefined","error":"Cannot read property 'replace' of undefined"}
  snyk Server error +1ms undefined
Error: Cannot read property 'replace' of undefined
    at /Users/spencerelliott/.nvm/versions/node/v4.2.2/lib/node_modules/snyk/lib/test.js:69:23
    at Request._callback (/Users/spencerelliott/.nvm/versions/node/v4.2.2/lib/node_modules/snyk/lib/request.js:47:5)
    at Request.self.callback (/Users/spencerelliott/.nvm/versions/node/v4.2.2/lib/node_modules/snyk/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/spencerelliott/.nvm/versions/node/v4.2.2/lib/node_modules/snyk/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/spencerelliott/.nvm/versions/node/v4.2.2/lib/node_modules/snyk/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
```

**Comment by remy** [comment]
Hi @elliottsj thanks for filing the issue and adding the debug info. We're looking at the issue now.

Going by the payload size, I'm expecting you're testing with a largish local project. Are you able to share your package.json file for the root of the project, or you can email support@snyk.io if you're rather keep it off this public repo. There might be something in there that can help debug.

Thanks.

**Comment by elliottsj** [comment]
It turns out I was missing `"name"` and `"version"` fields in package.json. After adding those fields, looks like snyk works! Maybe worth validating package.json files as part of snyk?

I can send my package.json privately if you're still interested.

**Comment by remy** [comment]
Thanks for following up. That sounds right that the name was missing and causing an exception on our side. I'll add validation against the `name` as you suggested.

Thanks again.
