### ISSUE TITLE
Graceful behaviour of Snyk API 500 error

### ISSUE THREAD

**Issue by k0nG** [snyk/snyk#73]
- `node -v`: v0.10.33
- `npm -v`: 2.13.5
- `snyk -v`: 1.25.2
- Command run: `snyk test`

### Expected behaviour
Test dependencies agains Snyk database. Exit with error if a dependency issue is found.

### Actual behaviour
Intermittent failures which seem to happen when Snyk gets a 500 error from its API. We've had this twice this week on builds. Repeating the build and running again seems to work fine. 

Ideally the snyk cli would fail gracefully when it cannot connnect to its API and therefore not cause our build to fail. At least this should be an option for those who are OK for their build to continue without a snyk test.

### Steps to reproduce
Running on CircleCI 1.0.
`snyk auth $SNYK_TOKEN && snyk test`

```
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: 500
    at /home/ubuntu/app/node_modules/snyk/lib/snyk-test/npm/index.js:101:23
    at /home/ubuntu/app/node_modules/snyk/lib/request.js:70:7
    at tryCatch (/home/ubuntu/app/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/home/ubuntu/app/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/home/ubuntu/app/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/home/ubuntu/app/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at process._tickCallback (node.js:419:13)
npm ERR! Test failed.  See above for more details.

npm test returned exit code 1
```

**Comment by lili2311** [comment]
👋 Closing this as it is outdated, please create a new issue if you are still seeing ungraceful behaviour
