### ISSUE TITLE
`snyk test` not working with Python 3

### ISSUE THREAD

**Issue by VihanAgarwal97** [snyk/snyk#730]
I am attempting to run a test through a script that I am calling in the `CMD` of a Docker container. Here is what my script looks like : 
```
#!/bin/sh
set -x;
set -e; set -o pipefail

snyk auth "$SNYK_TOKEN"

FILE=/somepath/requirements.txt
if test -f "$FILE"; then
    pip install -r requirements.txt
fi

output="$(snyk test)" && exit 0;
clean_output=$(echo "$output" 2>&1 | sed '1d;2d;')

do something with clean_output
``` 
However,`snyk test` fails to scan and asks me to run `pip install -r requirements.txt` even though it has already been run.
``` 
+ FILE=/somepath/requirements.txt
+ test -f /somepath/requirements.txt
+ pip install -r requirements.txt
Collecting asn1crypto==0.24.0 (from -r requirements.txt (line 1))
  Downloading 
...
https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
Installing collected packages: asn1crypto, certifi, pycparser, cffi, chardet, click, idna, six, cryptography, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, SQLAlchemy, Flask-SQLAlchemy, healthcheck, marshmallow, numpy, python-dateutil, pytz, pandas, prometheus-client, prometheus-flask-exporter, PyMySQL, PyYAML, urllib3, requests, scipy, uWSGI
  Running setup.py install for pycparser: started
    Running setup.py install for pycparser: finished with status 'done'
...
  Running setup.py install for uWSGI: started
    Running setup.py install for uWSGI: finished with status 'done'
Successfully installed Flask-1.0.2 Flask-SQLAlchemy-2.4.0 Jinja2-2.10.1 MarkupSafe-1.0 PyMySQL-0.9.2 PyYAML-3.13 SQLAlchemy-1.3.3 Werkzeug-0.14.1 asn1crypto-0.24.0 certifi-2019.3.9 cffi-1.11.5 chardet-3.0.4 click-6.7 cryptography-2.3.1 healthcheck-1.3.3 idna-2.7 itsdangerous-0.24 marshmallow-2.19.2 numpy-1.15.1 pandas-0.23.4 prometheus-client-0.6.0 prometheus-flask-exporter-0.5.1 pycparser-2.18 python-dateutil-2.7.3 pytz-2018.5 requests-2.21.0 scipy-1.2.1 six-1.11.0 uWSGI-2.0.18 urllib3-1.24.2
+ snyk test
+ output='Required packages missing: asn1crypto, certifi, cffi, chardet, click, cryptography, flask, flask-sqlalchemy, healthcheck, idna, itsdangerous, jinja2, markupsafe, marshmallow, numpy, pandas, prometheus-client, prometheus-flask-exporter, pycparser, pymysql, python-dateutil, pytz, pyyaml, requests, scipy, six, sqlalchemy, urllib3, uwsgi, werkzeug

Please run `pip install -r requirements.txt`
```

**Comment by VihanAgarwal97** [comment]
Here is the output with the `--debug` flag:
```
+ snyk test --debug
2019-08-12T18:57:04.412Z snyk test { _: [ [Circular] ], debug: true }
2019-08-12T18:57:04.812Z snyk Failed to test 1 projects, errors:
2019-08-12T18:57:04.814Z snyk error: FailedToRunTestError: Required packages missing: asn1crypto, certifi, cffi, chardet, click, cryptography, flask, flask-sqlalchemy, healthcheck, idna, itsdangerous, jinja2, markupsafe, marshmallow, numpy, pandas, prometheus-client, prometheus-flask-exporter, pycparser, pymysql, python-dateutil, pytz, pyyaml, requests, scipy, six, sqlalchemy, urllib3, uwsgi, werkzeug

Please run `pip install -r requirements.txt`
    at /snapshot/snyk/dist/lib/snyk-test/run-test.js:110:19
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/snyk/dist/lib/snyk-test/run-test.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2019-08-12T18:57:04.818Z snyk analytics { args: [ { debug: true, org: undefined, showVulnPaths: true } ],
  command: 'bad-command',
  metadata:
   { local: true,
     'error-message': '\nTesting /somepath...\n\nRequired packages missing: asn1crypto, certifi, cffi, chardet, click, cryptography, flask, flask-sqlalchemy, healthcheck, idna, itsdangerous, jinja2, markupsafe, marshmallow, numpy, pandas, prometheus-client, prometheus-flask-exporter, pycparser, pymysql, python-dateutil, pytz, pyyaml, requests, scipy, six, sqlalchemy, urllib3, uwsgi, werkzeug\n\nPlease run `pip install -r requirements.txt`',
     error: 'Error: \nTesting /somepath...\n\nRequired packages missing: asn1crypto, certifi, cffi, chardet, click, cryptography, flask, flask-sqlalchemy, healthcheck, idna, itsdangerous, jinja2, markupsafe, marshmallow, numpy, pandas, prometheus-client, prometheus-flask-exporter, pycparser, pymysql, python-dateutil, pytz, pyyaml, requests, scipy, six, sqlalchemy, urllib3, uwsgi, werkzeug\n\nPlease run `pip install -r requirements.txt`\n    at /snapshot/snyk/dist/cli/commands/test/index.js:157:27\n    at Generator.throw (<anonymous>)\n    at rejected (/snapshot/snyk/dist/cli/commands/test/index.js:5:65)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)',
     'error-code': 500,
     command: 'test' },
  version: '1.216.0',
  os: 'Linux 4.9',
  nodeVersion: 'v8.16.0',
  id: '8497e0bf353e4530ca1bfe2eaa2bbe44686e9390',
  ci: false,
  durationMs: 428 }
2019-08-12T18:57:04.819Z snyk Exit code: 2
2019-08-12T18:57:04.822Z snyk sending request to: https://snyk.io/api/v1/analytics/cli
2019-08-12T18:57:04.822Z snyk request body size: 1454
2019-08-12T18:57:04.823Z snyk gzipped request body size: 630
2019-08-12T18:57:04.823Z snyk not using proxy
```

**Comment by VihanAgarwal97** [comment]
Turns out the issue was with python versioning. I updated my language settings on the Web UI to use `Python 3` but that didn't help. Running `snyk test --command=python3` worked though, but since I want this script to be project independent, this won't work. Is there another work around?

**Comment by VihanAgarwal97** [comment]
Closing because https://github.com/snyk/snyk-python-plugin/issues/32 fixed it
