### ISSUE TITLE
snyk protect throws exception (via node 0.10.x)

### ISSUE THREAD

**Issue by remy** [snyk/snyk#78]
- `node -v`: 0.1042
- `npm -v`: 2.14.19
- `snyk -v`: (actually cases the error, but 1.29.0)
- Command run: `node_modules/.bin/snyk -v`

This also means local installs of jsbin's `npm install` bails with:

```
> jsbin@3.41.10 prepublish /Users/remy/Sites/jsbin-v3.17.15
> npm run snyk-protect


> jsbin@3.41.10 snyk-protect /Users/remy/Sites/jsbin-v3.17.15
> snyk protect


TypeError: Not an integer
    at Object.fs.writeSync (fs.js:540:18)
    at Function.writeFileSync [as sync] (/Users/remy/Sites/jsbin-v3.17.15/node_modules/snyk/node_modules/configstore/node_modules/write-file-atomic/index.js:114:10)
    at Object.create.all.set (/Users/remy/Sites/jsbin-v3.17.15/node_modules/snyk/node_modules/configstore/index.js:62:21)
    at Object.Configstore (/Users/remy/Sites/jsbin-v3.17.15/node_modules/snyk/node_modules/configstore/index.js:27:11)
    at Object.<anonymous> (/Users/remy/Sites/jsbin-v3.17.15/node_modules/snyk/lib/user-config.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

### Expected behaviour

Can read the version number of snyk.

### Actual behaviour

Crashes.

### Steps to reproduce

Using given versions, `node_modules/.bin/snyk -v`

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
👋 @remy 

We do not support Node.js 0.10, thinking about dropping 0.12 as well. Will not do so before 8 kicks in, but 0.10 is below the red line.
