### ISSUE TITLE
 Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ashirman** [snyk/snyk#867]
- `node -v`: v10.16.0
- `npm -v`: 6.9.0
- `snyk -v`: 1.227.0
- Command run:

`snyk --org=<orgnamhere> test --dev --severity-threshold=high`

### Expected behaviour
can run snyk

### Actual behaviour
can not run snyk at all

the stacktrace as the following
```
TypeError: Cannot read property 'type' of undefined
    at constructPatchesText (/home/travis/build/pleo-io/deimos/node_modules/snyk/src/cli/commands/test/formatters/remediation-based-format-issues.ts:170:27)
    at Object.formatIssuesWithRemediation (/home/travis/build/pleo-io/deimos/node_modules/snyk/src/cli/commands/test/formatters/remediation-based-format-issues.ts:97:28)
    at displayResult (/home/travis/build/pleo-io/deimos/node_modules/snyk/src/cli/commands/test/index.ts:341:29)
    at results.map (/home/travis/build/pleo-io/deimos/node_modules/snyk/src/cli/commands/test/index.ts:155:25)
    at Array.map (<anonymous>)
    at /home/travis/build/pleo-io/deimos/node_modules/snyk/src/cli/commands/test/index.ts:155:6
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/pleo-io/deimos/node_modules/snyk/dist/cli/commands/test/index.js:4:58)
```

### Steps to reproduce

workaround: run `yarn upgrade nyc`

---
it seems like one of the the vulnerability metadata is missing a property.

**Comment by lili2311** [comment]
👋 Please could you verify if you still seeing this issue on the latest version of the CLI

**Comment by lili2311** [comment]
@ashirman is this still an issue for you on latest cli version?

**Comment by lili2311** [comment]
Closing this as we haven't heard back for a while, please re-open if needed.
