### ISSUE TITLE
Unable to check firebase-admin NPM

### ISSUE THREAD

**Issue by motss** [snyk/snyk#91]
- `node -v`: **8.1.2**
- `npm -v`: **5.0.3**
- `snyk -v`: **1.35.0**
- Command run: `snyk test`

### Expected behaviour
The test passes without any issues/  or vulnerabilities.

### Actual behaviour
Unable to pass the test with command `snyk test` and shows the error `Invalid Version: https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-7.2.0.tgz`.

### Steps to reproduce
1. Make a new directory.
2. Run `npm init` and `npm i firebase-admin && npm i -D snyk`.
3. Run `snyk wizard` as `firebase-admin` is suffering from a vulnerability issue, then follow the configuration below for patching:

    ```
    Remediation options Patch
    ? Add `snyk test` to package.json file to fail test on newly disclosed vulnerabilities?
    This will require authentication via `snyk auth` when running tests. No
    ? Add `snyk protect` as a package.json installation hook to apply chosen patches on install? No
    ```
4. Run `rm -rf node_modules` and then `npm i` to reinstall packages.
5. Run `snyk test` and you'll see the error message that halt the checking process: `Invalid Version: https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-7.2.0.tgz`.

### Refs to possible related issues
* https://github.com/firebase/firebase-admin-node/issues/42

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

```
  snyk test { _: [ [Circular] ], debug: true } +0ms
  snyk checking for cli updates +427ms
  snyk add local true +53ms
  snyk add error-message Invalid Version: https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-7.2.0.tgz +835ms
  snyk add error TypeError: Invalid Version: https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-7.2.0.tgz
    at new SemVer (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/semver/semver.js:293:11)
    at Range.test (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/semver/semver.js:1085:16)
    at /Users/rongsenng/Google Drive/motss/test-snyk/node_modules/snyk-resolve-deps/lib/deps.js:153:28
    at Array.reduce (native)
    at /Users/rongsenng/Google Drive/motss/test-snyk/node_modules/snyk-resolve-deps/lib/deps.js:134:13
    at tryCatch (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:121:5) +0ms
  snyk add error-code undefined +0ms
  snyk add command test +1ms
TypeError: Invalid Version: https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-7.2.0.tgz
    at new SemVer (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/semver/semver.js:293:11)
    at Range.test (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/semver/semver.js:1085:16)
    at /Users/rongsenng/Google Drive/motss/test-snyk/node_modules/snyk-resolve-deps/lib/deps.js:153:28
    at Array.reduce (native)
    at /Users/rongsenng/Google Drive/motss/test-snyk/node_modules/snyk-resolve-deps/lib/deps.js:134:13
    at tryCatch (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:121:5)
  snyk { command: 'bad-command',
  snyk   args: [ { debug: true, packageManager: 'npm' } ],
  snyk   metadata:
  snyk    { local: true,
  snyk      'error-message': 'Invalid Version: https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-7.2.0.tgz',
  snyk      error: 'TypeError: Invalid Version: https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-7.2.0.tgz\n    at new SemVer (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/semver/semver.js:293:11)\n    at Range.test (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/semver/semver.js:1036:15)\n    at Function.satisfies (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/semver/semver.js:1085:16)\n    at /Users/rongsenng/Google Drive/motss/test-snyk/node_modules/snyk-resolve-deps/lib/deps.js:153:28\n    at Array.reduce (native)\n    at /Users/rongsenng/Google Drive/motss/test-snyk/node_modules/snyk-resolve-deps/lib/deps.js:134:13\n    at tryCatch (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)\n    at invokeCallback (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)\n    at publish (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)\n    at flush (/Users/rongsenng/Google Drive/motss/test-snyk/node_modules/es6-promise/dist/es6-promise.js:121:5)',
  snyk      'error-code': undefined,
  snyk      command: 'test' },
  snyk   version: '1.35.0',
  snyk   os: 'OS X',
  snyk   nodeVersion: 'v8.1.2',
  snyk   id: 'ebdf43a5a6277e1afa63d5b853783c08f96a6630',
  snyk   ci: false } +10ms
```

**Comment by adrukh** [comment]
@motss we've seen this issue before, seems related to npm5. See more here - https://github.com/mapbox/node-pre-gyp/issues/298

Please let me know if the suggestions on that thread work for you.

**Comment by daton89** [comment]
i have the same problem here! with npm5... i've solved with: 

`rm ./package-lock.json && npm i`

and it worked!
