### ISSUE TITLE
[🐛] --all-projects barfs stack traces on missing node_modules folders

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#993]
- `node -v`: 13.3.0
- `npm -v`: 6.13.1
- `snyk -v`: 1.290.1
- Command run: `snyk test --all-projects --detection-depth=5`

### Expected behaviour
No bunch of stack traces

### Actual behaviour

```
C:\Users\JesseHouwing\source\repos\PartsUnlimited>snyk test --all-projects --detection-depth=5
Error: Missing node_modules folder: we can't test without dependencies.
Please run 'npm install' first.
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\npm-modules-parser.ts:22:11)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:4:12)
    at Object.parse (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:18:12)
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\index.ts:22:27)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\index.js:8:71
    at new Promise (<anonymous>)
Error: Missing node_modules folder: we can't test without dependencies.
Please run 'npm install' first.
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\npm-modules-parser.ts:22:11)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:4:12)
    at Object.parse (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:18:12)
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\index.ts:22:27)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\index.js:8:71
    at new Promise (<anonymous>)
Error: Missing node_modules folder: we can't test without dependencies.
Please run 'npm install' first.
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\npm-modules-parser.ts:22:11)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:4:12)
    at Object.parse (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:18:12)
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\index.ts:22:27)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\index.js:8:71
    at new Promise (<anonymous>)
Error: Missing node_modules folder: we can't test without dependencies.
Please run 'npm install' first.
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\npm-modules-parser.ts:22:11)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:4:12)
    at Object.parse (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:18:12)
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\index.ts:22:27)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\index.js:8:71
    at new Promise (<anonymous>)
Error: Missing node_modules folder: we can't test without dependencies.
Please run 'npm install' first.
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\npm-modules-parser.ts:22:11)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:4:12)
    at Object.parse (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:18:12)
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\index.ts:22:27)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\index.js:8:71
    at new Promise (<anonymous>)
Error: Missing node_modules folder: we can't test without dependencies.
Please run 'npm install' first.
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\npm-modules-parser.ts:22:11)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:4:12)
    at Object.parse (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:18:12)
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\index.ts:22:27)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\index.js:8:71
    at new Promise (<anonymous>)
Error: Missing node_modules folder: we can't test without dependencies.
Please run 'npm install' first.
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\npm-modules-parser.ts:22:11)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:4:12)
    at Object.parse (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\npm-modules-parser.js:18:12)
    at Object.<anonymous> (C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\src\lib\plugins\nodejs-plugin\index.ts:22:27)
    at Generator.next (<anonymous>)
    at C:\Users\JesseHouwing\AppData\Roaming\npm\node_modules\snyk\dist\lib\plugins\nodejs-plugin\index.js:8:71
    at new Promise (<anonymous>)
```

### Steps to reproduce

Clone: https://github.com/jessehouwing/PartsUnlimited
Run: `pwsh build.ps1 Release . .\dist`
Run: `snyk test --all-projects --detection-depth=5`

---

To work around, ignore the `bower_components` folder:

`C:\Users\JesseHouwing\source\repos\PartsUnlimited>snyk test --all-projects --detection-depth=5 --exclude=bower_components`

```  'C:\\Users\\JesseHouwing\\source\\repos\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\bower_components\\bootstrap\\Gemfile.lock',
  'C:\\Users\\JesseHouwing\\source\\repos\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\bower_components\\bootstrap\\package.json',
  'C:\\Users\\JesseHouwing\\source\\repos\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\bower_components\\jquery-ui\\package.json',
  'C:\\Users\\JesseHouwing\\source\\repos\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\bower_components\\jquery-ui-smoothness\\package.json',
  'C:\\Users\\JesseHouwing\\source\\repos\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\bower_components\\jquery-validation\\package.json',
  'C:\\Users\\JesseHouwing\\source\\repos\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\bower_components\\jquery-zoom\\package.json',
  'C:\\Users\\JesseHouwing\\source\\repos\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\bower_components\\modernizr\\package.json',
  'C:\\Users\\JesseHouwing\\source\\repos\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\bower_components\\respond\\package.json',
```

**Comment by joaolemos** [comment]
Hi @jessehouwing. 👋 

Thanks for reporting this, and all the detailed information. We've now added it to our backlog to be addressed, and the right team will be investigating this soon 👍

**Comment by lili2311** [comment]
Please try again with version `1.300.0` you can see the errors when using `-d` output
